import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Alert,Pressable,Text,View} from 'react-native';
import {supabase} from '../lib/supabase';
import {createCosmeticSetActions} from './cosmeticSets';
import PropArtwork from './PropArtwork';
export default function CosmeticSetsPanel({catalog=[],ownerGrant=null,onChanged,onPreview}){
 const [sets,setSets]=useState([]),[category,setCategory]=useState('normal'),[page,setPage]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState('');const alive=useRef(true),confirmation=useRef(false),actions=useRef(createCosmeticSetActions((name,args)=>supabase.rpc(name,args)));
 useEffect(()=>{alive.current=true;supabase.from('cosmetic_sets_v142').select('*').eq('active',true).order('sort_order').then(({data,error})=>{if(!alive.current)return;if(error)setError(error.message);else setSets(data||[]);}).catch(e=>{if(alive.current)setError(e.message||'Could not load matching sets.');});return()=>{alive.current=false;};},[]);
 const categories=useMemo(()=>[...new Set(sets.map(s=>s.category))],[sets]);const rows=sets.filter(s=>s.category===category),shown=rows.slice(page*12,page*12+12);
 const submit=set=>{if(busy||confirmation.current)return;const matching=catalog.filter(x=>x.visual?.set_code===set.code),sale=matching.filter(x=>x.purchasable);if(ownerGrant){if(!Number.isSafeInteger(ownerGrant.publicId)||ownerGrant.publicId<1||ownerGrant.days!==null&&(!Number.isSafeInteger(ownerGrant.days)||ownerGrant.days<1||ownerGrant.days>3650)||String(ownerGrant.reason||'').trim().length<5){setError('Enter permanent User ID, valid days and a reason first.');return;}}else if(set.official||!sale.length){setError('Benefit / Owner assignment only');return;}
 confirmation.current=true;Alert.alert(ownerGrant?'Grant matching set?':'Buy matching set?',ownerGrant?`${set.name} • ID ${ownerGrant.publicId} • ${ownerGrant.days===null?'Permanent':ownerGrant.days+' days'}`:`${set.name} • ${sale.reduce((sum,x)=>sum+Number(x.price_coins||0),0).toLocaleString()} coins maximum; active owned items cost zero.`,[{text:'Cancel',style:'cancel',onPress:()=>{confirmation.current=false;}},{text:ownerGrant?'GRANT':'BUY',onPress:async()=>{confirmation.current=false;if(!alive.current)return;setBusy(true);setError('');try{await actions.current.run(set,ownerGrant);if(alive.current){onChanged?.();Alert.alert('Saved',ownerGrant?'Set granted to the selected ID.':'Purchased and equipped.');}}catch(e){if(alive.current)setError(e.message);}finally{if(alive.current)setBusy(false);}}}],{cancelable:false});};
 if(!sets.length&&!error)return null;
 return <View style={{marginVertical:12,padding:12,borderRadius:18,backgroundColor:'#171125'}}><Text style={{color:'#FBECCB',fontWeight:'900'}}>MATCHING SETS</Text>{error?<Text style={{color:'#F79DB7',marginVertical:8}}>{error}</Text>:null}<View style={{flexDirection:'row',flexWrap:'wrap',gap:6,marginVertical:10}}>{categories.map(c=><Pressable key={c} onPress={()=>{setCategory(c);setPage(0)}} style={{padding:9,borderRadius:14,backgroundColor:category===c?'#6942BF':'#292037'}}><Text style={{color:'#FFF',fontSize:10}}>{c.toUpperCase()}</Text></Pressable>)}</View>{shown.map(set=>{const items=catalog.filter(x=>x.visual?.set_code===set.code);return <View key={set.code} style={{paddingVertical:12,borderTopWidth:1,borderColor:'#493454'}}><Text style={{color:'#FFF',fontWeight:'800'}}>{set.name}</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:8,marginVertical:8}}>{items.map(item=><Pressable key={item.code} accessibilityLabel={'Preview '+item.name} onPress={()=>onPreview?.(item)}><PropArtwork item={item} size={56}/><Text style={{color:'#BEAEC9',fontSize:8,width:56,textAlign:'center'}}>{item.kind.replace('_',' ')}</Text></Pressable>)}</View><Pressable disabled={busy||(!ownerGrant&&(set.official||!items.some(x=>x.purchasable)))} onPress={()=>submit(set)} style={{padding:12,borderRadius:14,backgroundColor:'#453070'}}><Text style={{color:'#FFE6A6',fontSize:11}}>{busy?'SAVING…':ownerGrant?'GRANT FULL SET':set.official||!items.some(x=>x.purchasable)?'BENEFIT / OWNER ASSIGNMENT':'BUY AVAILABLE ITEMS'}</Text></Pressable></View>})}<View style={{flexDirection:'row',justifyContent:'space-between',marginTop:8}}><Pressable disabled={page===0} onPress={()=>setPage(v=>v-1)}><Text style={{color:'#85E4F0'}}>PREVIOUS</Text></Pressable><Text style={{color:'#CCC'}}>{page+1} / {Math.max(1,Math.ceil(rows.length/12))}</Text><Pressable disabled={(page+1)*12>=rows.length} onPress={()=>setPage(v=>v+1)}><Text style={{color:'#85E4F0'}}>NEXT</Text></Pressable></View></View>;
}

