import TextInput from './DraftTextInput';
import React,{useMemo,useState} from 'react';
import {Modal,Pressable,SafeAreaView,StyleSheet,Text,View} from 'react-native';
const pad=n=>String(n).padStart(2,'0');
const format=(d,time)=>time?`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`:`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
export default function DateTimeField({value='',onChange,label='DATE / TIME',includeTime=false,placeholder}){
 const [open,setOpen]=useState(false),[cursor,setCursor]=useState(()=>{const d=new Date(value||Date.now());return Number.isNaN(d.getTime())?new Date():d});
 const days=useMemo(()=>{const y=cursor.getFullYear(),m=cursor.getMonth(),first=new Date(y,m,1).getDay(),last=new Date(y,m+1,0).getDate();return [...Array(first).fill(null),...Array.from({length:last},(_,i)=>i+1)]},[cursor]);
 const select=day=>{if(!day)return;const d=new Date(cursor.getFullYear(),cursor.getMonth(),day);const old=new Date(value||Date.now());if(includeTime&&!Number.isNaN(old.getTime()))d.setHours(old.getHours(),old.getMinutes());onChange(format(d,includeTime));setOpen(false)};
 return <View style={s.wrap}><Text style={s.label}>{label}</Text><View style={s.row}><TextInput value={value} onChangeText={onChange} placeholder={placeholder||(includeTime?'YYYY-MM-DD HH:MM':'YYYY-MM-DD')} placeholderTextColor="#737B8E" style={s.input}/><Pressable onPress={()=>setOpen(true)} style={s.pick}><Text style={s.pickText}>CALENDAR</Text></Pressable></View><Modal visible={open} transparent animationType="fade" onRequestClose={()=>setOpen(false)}><SafeAreaView style={s.shade}><View style={s.card}><View style={s.head}><Pressable onPress={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()-1,1))} style={s.arrow}><Text style={s.arrowText}>‹</Text></Pressable><Text style={s.month}>{cursor.toLocaleString(undefined,{month:'long',year:'numeric'})}</Text><Pressable onPress={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()+1,1))} style={s.arrow}><Text style={s.arrowText}>›</Text></Pressable></View><View style={s.grid}>{['S','M','T','W','T','F','S'].map((x,i)=><Text key={i} style={s.week}>{x}</Text>)}{days.map((day,i)=><Pressable key={i} disabled={!day} onPress={()=>select(day)} style={s.day}><Text style={s.dayText}>{day||''}</Text></Pressable>)}</View><View style={s.actions}><Pressable onPress={()=>onChange('')} style={s.secondary}><Text style={s.secondaryText}>CLEAR</Text></Pressable><Pressable onPress={()=>{const now=new Date();setCursor(now);onChange(format(now,includeTime));setOpen(false)}} style={s.primary}><Text style={s.primaryText}>TODAY</Text></Pressable><Pressable onPress={()=>setOpen(false)} style={s.secondary}><Text style={s.secondaryText}>CLOSE</Text></Pressable></View></View></SafeAreaView></Modal></View>;
}
const s=StyleSheet.create({wrap:{marginTop:8},label:{color:'#5FE2FF',fontSize:7,fontWeight:'900',marginBottom:5},row:{flexDirection:'row',gap:7},input:{flex:1,minHeight:45,borderRadius:12,backgroundColor:'#0D1019',borderWidth:1,borderColor:'#30364A',color:'#F8F9FF',paddingHorizontal:11},pick:{minWidth:82,borderRadius:12,backgroundColor:'#5039BB',alignItems:'center',justifyContent:'center'},pickText:{color:'#fff',fontSize:7,fontWeight:'900'},shade:{flex:1,backgroundColor:'#000B',justifyContent:'center',padding:18},card:{borderRadius:22,backgroundColor:'#151A27',borderWidth:1,borderColor:'#464F69',padding:14},head:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},month:{color:'#F8F9FF',fontSize:16,fontWeight:'900'},arrow:{width:42,height:40,borderRadius:12,backgroundColor:'#232A3B',alignItems:'center',justifyContent:'center'},arrowText:{color:'#5FE2FF',fontSize:25},grid:{flexDirection:'row',flexWrap:'wrap',marginTop:12},week:{width:'14.28%',color:'#9199AD',textAlign:'center',fontSize:8,fontWeight:'900',paddingVertical:7},day:{width:'14.28%',height:42,alignItems:'center',justifyContent:'center'},dayText:{color:'#F8F9FF',fontSize:11,fontWeight:'800'},actions:{flexDirection:'row',gap:7,marginTop:10},primary:{flex:1,minHeight:42,borderRadius:12,backgroundColor:'#7558FF',alignItems:'center',justifyContent:'center'},secondary:{flex:1,minHeight:42,borderRadius:12,backgroundColor:'#232A3B',alignItems:'center',justifyContent:'center'},primaryText:{color:'#fff',fontSize:8,fontWeight:'900'},secondaryText:{color:'#5FE2FF',fontSize:8,fontWeight:'900'}});

