import {httpsMedia} from './catalogMedia';

// Actual original generated media. This resolver never grants ownership or roles.
const ART={
 'funnyroom-frame':require('../assets/brand152/frame.webp'),
 'funnyroom-room-frame':require('../assets/brand152/roomframe.webp'),
 'funnyroom-entry':require('../assets/brand152/entry.webp'),
 'funnyroom-bubble':require('../assets/brand152/bubble.webp'),
 'funnyroom-medal':require('../assets/brand152/medal.webp'),
 'dragon-ivory':require('../assets/dragon147/ivory-poses.png'),
 'dragon-crimson':require('../assets/dragon147/crimson-poses.png'),
 'dragon-emerald':require('../assets/dragon147/emerald-poses.png'),
 'nameplate-sapphire':require('../assets/props142/nameplate-sapphire.webp'),
 'theme-birthday':require('../assets/props142/theme-birthday.webp'),
 'nameplate-birthday':require('../assets/props142/nameplate-birthday.webp'),
 'noble-rose':require('../assets/props142/noble-rose.webp'),
 'nameplate-rose':require('../assets/props142/nameplate-rose.webp'),
 'theme-romance':require('../assets/props142/theme-romance.webp'),
 'nameplate':require('../assets/props142/nameplate.webp'),
 'theme-funny':require('../assets/props142/theme-funny.webp'),
 'frame-rocket':require('../assets/props142/frame-rocket.webp'),
 'palace':require('../assets/props142/palace.webp'),
 'room-frame-sapphire':require('../assets/props142/room-frame-sapphire.webp'),
 'theme-family':require('../assets/props142/theme-family.webp'),
 'room-frame-birthday':require('../assets/props142/room-frame-birthday.webp'),
 'noble-emerald':require('../assets/props142/noble-emerald.webp'),
 'theme-rocket':require('../assets/props142/theme-rocket.webp'),
 'nameplate-emerald':require('../assets/props142/nameplate-emerald.webp'),
 'noble-birthday':require('../assets/props142/noble-birthday.webp'),
 'theme-professional':require('../assets/props142/theme-professional.webp'),
 'room-frame':require('../assets/props142/room-frame.webp'),
 'frame-family':require('../assets/props142/frame-family.webp'),
 'frame-cp':require('../assets/props142/frame-cp.webp'),
 'noble-sapphire':require('../assets/props142/noble-sapphire.webp'),
 'noble':require('../assets/props142/noble.webp'),
 'frame-birthday':require('../assets/props142/frame-birthday.webp'),
 'theme-fire':require('../assets/props142/theme-fire.webp'),
 'room-frame-rose':require('../assets/props142/room-frame-rose.webp'),
 'room-frame-emerald':require('../assets/props142/room-frame-emerald.webp'),

 'frame-amethyst':require('../assets/props140/frame-amethyst.png'),
 'frame-rose':require('../assets/props140/frame-rose.png'),
 'frame-lunar':require('../assets/props140/frame-lunar.png'),
 'frame-bloom':require('../assets/props140/frame-bloom.png'),
 'frame-solar':require('../assets/props140/frame-solar.png'),
 'badge':require('../assets/props140/badge.png'),
 'medal':require('../assets/props140/medal.png'),
 'bubble-royal':require('../assets/props140/bubble-royal.png'),
 'bubble-love':require('../assets/props140/bubble-love.png'),
 'bubble-funny':require('../assets/props140/bubble-funny.png'),
};
const SCENES={
 'wink':[require('../assets/props140/entry-wink-0.jpg'),require('../assets/props140/entry-wink-1.jpg'),require('../assets/props140/entry-wink-2.jpg'),require('../assets/props140/entry-wink-3.jpg')],
 'couple':[require('../assets/props140/entry-couple-0.jpg'),require('../assets/props140/entry-couple-1.jpg'),require('../assets/props140/entry-couple-2.jpg'),require('../assets/props140/entry-couple-3.jpg')],
 'horse':[require('../assets/props140/entry-horse-0.jpg'),require('../assets/props140/entry-horse-1.jpg'),require('../assets/props140/entry-horse-2.jpg'),require('../assets/props140/entry-horse-3.jpg')],
 'orbit':[require('../assets/props140/entry-orbit-0.jpg'),require('../assets/props140/entry-orbit-1.jpg'),require('../assets/props140/entry-orbit-2.jpg'),require('../assets/props140/entry-orbit-3.jpg')],
 'portal':[require('../assets/props140/entry-portal-0.jpg'),require('../assets/props140/entry-portal-1.jpg'),require('../assets/props140/entry-portal-2.jpg'),require('../assets/props140/entry-portal-3.jpg')],
};
const ALIASES={
 "badge_heartbond": "badge",
 "badge_host": "badge",
 "badge_noble_royal": "badge",
 "badge_official": "badge",
 "badge_room_star": "badge",
 "badge_vip_legend": "badge",
 "cp_weekly_badge": "badge",
 "rocket_bronze_badge": "badge",
 "svip_badge_1": "badge",
 "svip_badge_10": "badge",
 "svip_badge_2": "badge",
 "svip_badge_3": "badge",
 "svip_badge_4": "badge",
 "svip_badge_5": "badge",
 "svip_badge_6": "badge",
 "svip_badge_7": "badge",
 "svip_badge_8": "badge",
 "svip_badge_9": "badge",
 "bubble_aurora_whisper": "bubble-royal",
 "bubble_comic": "bubble-funny",
 "bubble_diamond": "bubble-royal",
 "bubble_vip_gold": "bubble-royal",
 "cp_weekly_car": "entry-couple",
 "entry_aurora_throne": "entry-portal",
 "entry_baraat_royal": "entry-horse",
 "entry_comet_drive": "entry-orbit",
 "entry_cosmic_train": "entry-orbit",
 "entry_desert_falcon": "entry-portal",
 "entry_funny_palace": "entry-portal",
 "entry_funny_pop": "entry-wink",
 "entry_galaxy_elephant": "entry-portal",
 "entry_heart_arrival": "entry-couple",
 "entry_host_spotlight": "entry-portal",
 "entry_neon_bike": "entry-orbit",
 "entry_noble_caravan": "entry-horse",
 "entry_official": "entry-portal",
 "entry_royal_jet": "entry-portal",
 "entry_vip_royal": "entry-portal",
 "rocket_gold_entry": "entry-portal",
 "cp_weekly_frame": "frame-amethyst",
 "frame_aurora_royal": "frame-amethyst",
 "frame_comet_night": "frame-lunar",
 "frame_crystal_wings": "frame-solar",
 "frame_desert_falcon": "frame-solar",
 "frame_diamond_orbit": "frame-lunar",
 "frame_host_stage": "frame-amethyst",
 "frame_lotus_crown": "frame-rose",
 "frame_moon_peacock": "frame-lunar",
 "frame_neon_heart": "frame-rose",
 "frame_neon_smile": "frame-bloom",
 "frame_neon_tiger": "frame-amethyst",
 "frame_noble_sun": "frame-solar",
 "frame_official_shield": "frame-solar",
 "frame_vip_crown": "frame-amethyst",
 "official_frame_admin": "frame-solar",
 "official_frame_agency_owner": "frame-solar",
 "official_frame_bd": "frame-solar",
 "official_frame_bd_leader": "frame-solar",
 "official_frame_co_owner": "frame-solar",
 "official_frame_coin_seller": "frame-solar",
 "official_frame_country_manager": "frame-solar",
 "official_frame_cs": "frame-solar",
 "official_frame_cs_leader": "frame-solar",
 "official_frame_event_manager": "frame-solar",
 "official_frame_host": "frame-solar",
 "official_frame_manager": "frame-solar",
 "official_frame_merchant": "frame-solar",
 "official_frame_moderator": "frame-solar",
 "official_frame_root_founder": "frame-solar",
 "official_frame_super_admin": "frame-solar",
 "official_frame_user": "frame-solar",
 "rocket_silver_frame": "frame-amethyst",
 "svip_frame_1": "frame-amethyst",
 "svip_frame_10": "frame-solar",
 "svip_frame_2": "frame-amethyst",
 "svip_frame_3": "frame-rose",
 "svip_frame_4": "frame-rose",
 "svip_frame_5": "frame-lunar",
 "svip_frame_6": "frame-lunar",
 "svip_frame_7": "frame-bloom",
 "svip_frame_8": "frame-bloom",
 "svip_frame_9": "frame-solar",
 "medal_contributor": "medal",
 "medal_pk_champion": "medal",
 "medal_room_legend": "medal",
 "ai140_frame_amethyst": "frame-amethyst",
 "ai140_frame_rose": "frame-rose",
 "ai140_frame_lunar": "frame-lunar",
 "ai140_frame_bloom": "frame-bloom",
 "ai140_frame_solar": "frame-solar",
 "ai140_entry_wink": "entry-wink",
 "ai140_entry_couple": "entry-couple",
 "ai140_entry_horse": "entry-horse",
 "ai140_entry_orbit": "entry-orbit",
 "ai140_entry_portal": "entry-portal",
 "ai140_bubble_royal": "bubble-royal",
 "ai140_bubble_love": "bubble-love",
 "ai140_bubble_funny": "bubble-funny",
 "ai140_medal_star": "medal",
 "ai140_badge_official": "badge",
 "role_frame_root_founder": "frame-amethyst",
 "role_badge_root_founder": "badge",
 "role_entry_root_founder": "entry-portal",
 "ai140_role_entry_root_founder": "entry-portal",
 "role_frame_co_owner": "frame-rose",
 "role_badge_co_owner": "badge",
 "role_entry_co_owner": "entry-portal",
 "ai140_role_entry_co_owner": "entry-portal",
 "role_frame_country_manager": "frame-lunar",
 "role_badge_country_manager": "badge",
 "role_entry_country_manager": "entry-portal",
 "ai140_role_entry_country_manager": "entry-portal",
 "role_frame_manager": "frame-bloom",
 "role_badge_manager": "badge",
 "role_entry_manager": "entry-portal",
 "ai140_role_entry_manager": "entry-portal",
 "role_frame_super_admin": "frame-solar",
 "role_badge_super_admin": "badge",
 "role_entry_super_admin": "entry-portal",
 "ai140_role_entry_super_admin": "entry-portal",
 "role_frame_admin": "frame-amethyst",
 "role_badge_admin": "badge",
 "role_entry_admin": "entry-portal",
 "ai140_role_entry_admin": "entry-portal",
 "role_frame_bd_leader": "frame-rose",
 "role_badge_bd_leader": "badge",
 "role_entry_bd_leader": "entry-portal",
 "ai140_role_entry_bd_leader": "entry-portal",
 "role_frame_bd": "frame-lunar",
 "role_badge_bd": "badge",
 "role_entry_bd": "entry-portal",
 "ai140_role_entry_bd": "entry-portal",
 "role_frame_agency_owner": "frame-bloom",
 "role_badge_agency_owner": "badge",
 "role_entry_agency_owner": "entry-portal",
 "ai140_role_entry_agency_owner": "entry-portal",
 "role_frame_host": "frame-solar",
 "role_badge_host": "badge",
 "role_entry_host": "entry-portal",
 "ai140_role_entry_host": "entry-portal",
 "role_frame_merchant": "frame-amethyst",
 "role_badge_merchant": "badge",
 "role_entry_merchant": "entry-portal",
 "ai140_role_entry_merchant": "entry-portal",
 "role_frame_coin_seller": "frame-rose",
 "role_badge_coin_seller": "badge",
 "role_entry_coin_seller": "entry-portal",
 "ai140_role_entry_coin_seller": "entry-portal",
 "role_frame_moderator": "frame-lunar",
 "role_badge_moderator": "badge",
 "role_entry_moderator": "entry-portal",
 "ai140_role_entry_moderator": "entry-portal",
 "role_frame_event_manager": "frame-bloom",
 "role_badge_event_manager": "badge",
 "role_entry_event_manager": "entry-portal",
 "ai140_role_entry_event_manager": "entry-portal",
 "role_frame_cs_leader": "frame-solar",
 "role_badge_cs_leader": "badge",
 "role_entry_cs_leader": "entry-portal",
 "ai140_role_entry_cs_leader": "entry-portal",
 "role_frame_cs": "frame-amethyst",
 "role_badge_cs": "badge",
 "role_entry_cs": "entry-portal",
 "ai140_role_entry_cs": "entry-portal",
 "role_frame_user": "frame-rose",
 "role_badge_user": "badge",
 "role_entry_user": "entry-portal",
 "ai140_role_entry_user": "entry-portal"
};

export function generatedPropKey(item){return item?.visual?.ai_asset_key||ALIASES[item?.code]||null;}
export function propSource(item,{poster=false}={}){
 const remote=httpsMedia(poster?(item?.visual?.poster_url||(!/[.]gif(?:[?#]|$)/i.test(item?.asset_url||'')?item?.asset_url:null)):item?.asset_url);
 if(remote)return {uri:remote};
 const key=item?.visual?.ai_set_art||generatedPropKey(item);
 return ART[key]||SCENES[key?.replace(/^entry-/,'')]?.[3]||null;
}
export function propScene(item){if(httpsMedia(item?.asset_url))return null;return SCENES[generatedPropKey(item)?.replace(/^entry-/,'')]||null;}
export function propSceneKey(item){return generatedPropKey(item)?.replace(/^entry-/,'')||'portal';}
export function propHalo(key){return key==='horse'?{x:.5,y:.13,size:.155}:key==='orbit'?{x:.5,y:.48,size:.35}:{x:.5,y:.60,size:.36};}
export const GENERATED_ROLES=["root_founder", "co_owner", "country_manager", "manager", "super_admin", "admin", "bd_leader", "bd", "agency_owner", "host", "merchant", "coin_seller", "moderator", "event_manager", "cs_leader", "cs", "user"];

