import React from 'react';
import {Image,Modal,Pressable,StyleSheet,Text,View} from 'react-native';

export const HOME_AI_THEME=Object.freeze({surface:'#100C1C',raised:'#20152F',gold:'#FFE6AF',muted:'#D2BEDF',active:'#533287'});
export const HOME_AI_ICONS=Object.freeze({
 disc:require('../assets/home-ai/disc-135.webp'),
 home:require('../assets/home-ai/home-127.webp'),moments:require('../assets/home-ai/moments-127.webp'),create:require('../assets/home-ai/create-127.webp'),inbox:require('../assets/home-ai/inbox-127.webp'),profile:require('../assets/home-ai/profile-127.webp'),my:require('../assets/home-ai/my-127.webp'),popular:require('../assets/home-ai/popular-127.webp'),games:require('../assets/home-ai/games-127.webp'),video:require('../assets/home-ai/video-127.webp'),search:require('../assets/home-ai/search-127.webp'),grid:require('../assets/home-ai/grid-127.webp'),list:require('../assets/home-ai/list-127.webp'),family:require('../assets/home-ai/family-127.webp'),rank:require('../assets/home-ai/rank-127.webp'),gear:require('../assets/home-ai/gear-127.webp'),cp:require('../assets/home-ai/cp-127.webp'),
 notifications:require('../assets/home-ai/notifications-127.webp'),system:require('../assets/home-ai/system-127.webp'),support:require('../assets/home-ai/support-127.webp'),like:require('../assets/home-ai/like-127.webp'),comment:require('../assets/home-ai/comment-127.webp'),gift:require('../assets/home-ai/gift-127.webp'),share:require('../assets/home-ai/share-127.webp'),copy:require('../assets/home-ai/copy-127.webp'),more:require('../assets/home-ai/more-127.webp'),photo:require('../assets/home-ai/photo-127.webp'),post:require('../assets/home-ai/post-127.webp'),done:require('../assets/home-ai/done-127.webp'),exit:require('../assets/home-ai/exit-127.webp'),keep:require('../assets/home-ai/keep-127.webp'),mic:require('../assets/home-ai/mic-127.webp'),speaker:require('../assets/home-ai/speaker-127.webp'),
music:require('../assets/home-ai/music-127.webp'),members:require('../assets/home-ai/members-127.webp'),mode:require('../assets/home-ai/mode-127.webp'),noise:require('../assets/home-ai/noise-127.webp'),pk:require('../assets/home-ai/pk-127.webp'),pocket:require('../assets/home-ai/pocket-127.webp'),clean:require('../assets/home-ai/clean-127.webp'),lock:require('../assets/home-ai/lock-127.webp'),lockchat:require('../assets/home-ai/lockchat-127.webp'),effects:require('../assets/home-ai/effects-127.webp'),visitors:require('../assets/home-ai/visitors-127.webp'),medal:require('../assets/home-ai/medal-127.webp'),wallet:require('../assets/home-ai/wallet-127.webp'),vip:require('../assets/home-ai/vip-127.webp'),tasks:require('../assets/home-ai/tasks-127.webp'),invite:require('../assets/home-ai/invite-127.webp'),
previous:require('../assets/home-ai/previous-127.webp'),pause:require('../assets/home-ai/pause-127.webp'),play:require('../assets/home-ai/play-127.webp'),next:require('../assets/home-ai/next-127.webp'),repeat:require('../assets/home-ai/repeat-127.webp'),shuffle:require('../assets/home-ai/shuffle-127.webp'),collapse:require('../assets/home-ai/collapse-127.webp'),close:require('../assets/home-ai/close-127.webp'),
});
// CP140: clip only the detached raster debris Owner identified; original art/scale stays intact.
export const HOME_AI_CLEAN_BOUNDS=Object.freeze({search:[7,5,94,93],support:[5,5,95,92],post:[8,2,89,79],visitors:[3,10,94,76],more:[8,28,96,64]});
export function HomeAIIcon({name,size=24,style}){
 const bounds=HOME_AI_CLEAN_BOUNDS[name],source=HOME_AI_ICONS[name]||HOME_AI_ICONS.gear;
 if(!bounds)return <Image testID={`ai-icon-${name}`} pointerEvents="none" accessible={false} source={source} resizeMode="contain" style={[{width:size,height:size},style]}/>;
 const [x1,y1,x2,y2]=bounds,scale=size/96;
 return <View pointerEvents="none" accessible={false} style={[{width:size,height:size},style]}><View style={{position:'absolute',left:x1*scale,top:y1*scale,width:(x2-x1)*scale,height:(y2-y1)*scale,overflow:'hidden'}}><Image testID={`ai-icon-${name}`} source={source} resizeMode="contain" accessible={false} style={{position:'absolute',left:-x1*scale,top:-y1*scale,width:size,height:size}}/></View></View>;
}
// CP132: Owner removed this repeated app-wide overlay; native controls and icons remain.
export function HomeAIFrame(){return null;}
export function HomeAIText({children,style,...props}){return <Text {...props} style={[s.text,{textShadowColor:'#251032',textShadowOffset:{width:0,height:1},textShadowRadius:2},style]}>{children}</Text>;}
export function HomeAIPressable({children,style,art=true,...props}){return <Pressable {...props} style={state=>[typeof style==='function'?style(state):style,state.pressed&&!props.disabled&&{opacity:.76}]}>{state=><>{typeof children==='function'?children(state):children}{art?<HomeAIFrame corner={14}/>:null}</>}</Pressable>;}
export function HomeAIButton({label,icon,selected=false,disabled=false,style,textStyle,onPress,accessibilityLabel,...props}){return <HomeAIPressable {...props} disabled={disabled} onPress={onPress} accessibilityRole="button" accessibilityLabel={accessibilityLabel||label} accessibilityState={{selected,disabled}} style={[s.button,{backgroundColor:selected?HOME_AI_THEME.active:HOME_AI_THEME.raised,opacity:disabled ? .45 : 1},style]}>{icon?<HomeAIIcon name={icon} size={18}/>:null}{label?<HomeAIText numberOfLines={1} adjustsFontSizeToFit style={[s.buttonText,textStyle]}>{label}</HomeAIText>:null}</HomeAIPressable>;}
export function HomeAIExitDialog({visible,onStay,onExit}){return <Modal visible={visible} transparent animationType="fade" onRequestClose={onStay}><View style={s.shade}><Pressable testID="app-exit-outside" accessibilityLabel="Stay in Funny Room" onPress={onStay} style={StyleSheet.absoluteFillObject}/><View accessibilityViewIsModal style={s.dialog}><HomeAIFrame corner={30}/><HomeAIIcon name="home" size={48}/><HomeAIText style={s.title}>Exit Funny Room?</HomeAIText><HomeAIText style={s.body}>Do you want to stay in Funny Room or close the application?</HomeAIText><View style={s.actions}><HomeAIButton label="STAY" icon="done" onPress={onStay} style={{flex:1}}/><HomeAIButton label="EXIT" icon="exit" onPress={onExit} style={{flex:1}}/></View></View></View></Modal>;}
export function HomeAIActionDialog({visible,title,message,actions=[],onClose}){return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={s.shade}><Pressable accessibilityLabel="Cancel dialog" onPress={onClose} style={StyleSheet.absoluteFillObject}/><View accessibilityViewIsModal style={s.dialog}><HomeAIFrame corner={30}/><HomeAIIcon name="clean" size={44}/><HomeAIText style={s.title}>{title}</HomeAIText><HomeAIText style={s.body}>{message}</HomeAIText><View style={[s.actions,{flexWrap:'wrap'}]}>{actions.map(a=><HomeAIButton key={a.label} label={a.label} onPress={a.onPress} style={{flexGrow:1}}/>)}</View></View></View></Modal>;}
const s=StyleSheet.create({text:{color:HOME_AI_THEME.gold,fontWeight:'800'},button:{minHeight:44,minWidth:44,paddingHorizontal:10,paddingVertical:6,borderRadius:14,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:4},buttonText:{fontSize:11,fontWeight:'900',flexShrink:1,textAlign:'center'},shade:{flex:1,backgroundColor:'#03020BD9',justifyContent:'center',alignItems:'center',padding:24},dialog:{width:'100%',maxWidth:420,backgroundColor:HOME_AI_THEME.surface,borderRadius:22,padding:28,alignItems:'center'},title:{fontSize:23,marginTop:12,textAlign:'center'},body:{fontSize:15,lineHeight:22,textAlign:'center',marginVertical:18},actions:{flexDirection:'row',gap:10,width:'100%'}});

