import React,{useEffect,useRef,useState} from 'react';
import {View,ScrollView,StyleSheet} from 'react-native';
import {HomeAIText as Text} from './HomeAIChrome';
import {AiPressable as Pressable} from './AiChrome';
import TextInput from './DraftTextInput';
import {dailyCoinRpc} from './dailyCoinGrantApi';
import {loadCosmeticCatalog} from './cosmeticSets';
import {supabase} from '../lib/supabase';
import PropPreview from './PropPreview';
const blank=()=>({coins:'0',frame_code:null,frame_days:'7'});
export default function OwnerDailySignInRewards(){
 const [policy,setPolicy]=useState(null),[draft,setDraft]=useState(null),[frames,setFrames]=useState([]),[day,setDay]=useState(0),[reason,setReason]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState(null);
 const alive=useRef(true),lock=useRef(false);
 const load=async()=>{if(lock.current)return;lock.current=true;setBusy(true);try{const [p,f]=await Promise.all([dailyCoinRpc('owner_load_daily_signin_v149'),loadCosmeticCatalog(supabase)]);if(alive.current){setPolicy(p);setDraft({...p,schedule:p.schedule.length?p.schedule.map(x=>({...x,coins:String(x.coins),frame_days:String(x.frame_days||7)})):[blank()]});setFrames(f.filter(x=>x.kind==='frame'));setError('');setDay(0);}}catch(e){if(alive.current)setError(e.message);}finally{lock.current=false;if(alive.current)setBusy(false);}};
 useEffect(()=>{alive.current=true;load();return()=>{alive.current=false;};},[]);
 const patch=(key,value)=>setDraft(d=>({...d,schedule:d.schedule.map((x,i)=>i===day?{...x,[key]:value}:x)}));
 const save=async()=>{if(!policy||!draft||lock.current)return;let schedule;try{schedule=draft.schedule.map(x=>{if(!/^\d+$/.test(x.coins)||Number(x.coins)>1e12)throw Error('Coins must be a whole amount from 0 to 1 trillion.');if(x.frame_code&&(!/^\d+$/.test(x.frame_days)||Number(x.frame_days)<1||Number(x.frame_days)>3650))throw Error('Frame validity must be 1–3650 days.');if(Number(x.coins)===0&&!x.frame_code)throw Error('Every reward day needs coins or a frame.');return {coins:Number(x.coins),frame_code:x.frame_code||null,frame_days:x.frame_code?Number(x.frame_days):null};});if(reason.trim().length<5)throw Error('Enter an audit reason of at least five characters.');if(!Number.isFinite(Date.parse(draft.starts_at))||(draft.ends_at&&(!Number.isFinite(Date.parse(draft.ends_at))||Date.parse(draft.ends_at)<=Date.parse(draft.starts_at))))throw Error('Enter valid start and end dates.');}catch(e){return setError(e.message);}
 lock.current=true;setBusy(true);try{const p=await dailyCoinRpc('owner_save_daily_signin_v149',{p_config:{enabled:draft.enabled,schedule,reset_on_missed:draft.reset_on_missed,starts_at:draft.starts_at,ends_at:draft.ends_at||null},p_revision:policy.revision,p_reason:reason.trim()});if(alive.current){setPolicy(p);setReason('');setError('Saved. Existing claims and wallet history are preserved.');}}catch(e){if(alive.current)setError(e.message);}finally{lock.current=false;if(alive.current)setBusy(false);}};
 const chosen=draft?.schedule[day];
 return <View style={s.card}><Text style={s.title}>Daily sign-in rewards</Text><Text style={s.help}>Set any cycle length up to 366 days. Coins and frame validity are separate. This schedule replaces the app-open daily reward while enabled; both use one reward-day ledger.</Text><B label="Reload sign-in settings" disabled={busy} onPress={load}/>{error?<Text accessibilityRole="alert" style={s.help}>{error}</Text>:null}{draft?<><B disabled={busy} label={draft.enabled?'Enabled · tap to pause':'Paused · tap to enable'} onPress={()=>setDraft(d=>({...d,enabled:!d.enabled}))}/><B disabled={busy} label={draft.reset_on_missed?'Missed day restarts cycle':'Missed day preserves progress'} onPress={()=>setDraft(d=>({...d,reset_on_missed:!d.reset_on_missed}))}/><F label="Starts at (ISO date)" value={draft.starts_at} disabled={busy} set={v=>setDraft(d=>({...d,starts_at:v}))}/><F label="Ends at (blank: no fixed end)" value={draft.ends_at||''} disabled={busy} set={v=>setDraft(d=>({...d,ends_at:v}))}/><ScrollView horizontal>{draft.schedule.map((x,i)=><B key={i} label={`${i===day?'✓ ':''}Day ${i+1}`} disabled={busy} onPress={()=>setDay(i)}/>)}</ScrollView><B label="Add reward day" disabled={busy||draft.schedule.length>=366} onPress={()=>{setDay(draft.schedule.length);setDraft(d=>({...d,schedule:[...d.schedule,blank()]}));}}/><B label="Remove selected day" disabled={busy||draft.schedule.length<=1} onPress={()=>{setDraft(d=>({...d,schedule:d.schedule.filter((_,i)=>i!==day)}));setDay(0);}}/><F label={`Day ${day+1} coins`} value={chosen?.coins||'0'} set={v=>patch('coins',v)} disabled={busy}/><Text style={s.help}>Choose a frame; the eye previews it before saving.</Text><B label="No frame" disabled={busy} onPress={()=>patch('frame_code',null)}/><ScrollView horizontal>{frames.map(f=><View key={f.code}><B label={`${chosen?.frame_code===f.code?'✓ ':''}${f.name}`} disabled={busy} onPress={()=>patch('frame_code',f.code)}/><B label={`👁 Preview ${f.name}`} onPress={()=>setPreview(f)}/></View>)}</ScrollView>{chosen?.frame_code?<F label="Frame validity in manual days" value={chosen.frame_days} set={v=>patch('frame_days',v)} disabled={busy}/>:null}<F label="Mandatory audit reason" value={reason} set={setReason} disabled={busy}/><B label={busy?'Saving…':'Save sign-in settings'} onPress={save} disabled={busy}/><Text style={s.help}>Recent sign-in claims</Text>{(policy.history||[]).map(x=><Text key={`${x.user_id}:${x.claim_date}`} style={s.help}>ID {x.public_id} · {x.claim_date} · day {x.cycle_day} · {x.reward.coins} coins · {x.reward.frame_code||'no frame'} {x.reward.frame_days?`(${x.reward.frame_days} days)`:''}</Text>)}</>:null}<PropPreview item={preview} user={{display_name:'Reward preview'}} previewOnly onClose={()=>setPreview(null)}/></View>;
}
const F=({label,value,set,disabled})=><View><Text style={s.help}>{label}</Text><TextInput accessibilityLabel={label} value={value} editable={!disabled} onChangeText={set} style={s.input}/></View>;
const B=({label,onPress,disabled})=><Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[s.button,disabled&&{opacity:.4}]}><Text style={s.text}>{label}</Text></Pressable>;
const s=StyleSheet.create({card:{padding:14,marginTop:16,backgroundColor:'#16162d',borderRadius:16},title:{color:'#fff',fontSize:18,fontWeight:'800'},help:{color:'#cbd5e1',marginVertical:8,fontSize:12},input:{backgroundColor:'#080d1c',color:'#fff',padding:12,borderRadius:8},button:{backgroundColor:'#6436b8',minHeight:44,padding:12,borderRadius:10,margin:4},text:{color:'#fff',fontWeight:'800'}});

