import {makeRequestId} from './requestId';
import {HomeAIText as Text} from './HomeAIChrome';
import TextInput from './DraftTextInput';
import {AiPressable as Pressable,AiBackdrop} from './AiChrome';
import React,{useEffect,useMemo,useState} from 'react';
import {ScrollView,StyleSheet,View} from 'react-native';
import {loadOwnerDailyBenefits,saveOwnerDailyBenefit} from './rechargeRewards';
const id=()=>makeRequestId();
export default function OwnerDailyBenefitsScreen({campaignId}){const[rows,setRows]=useState([]),[selected,setSelected]=useState(null),[day,setDay]=useState('0'),[zone,setZone]=useState('UTC'),[policy,setPolicy]=useState('same_day'),[grace,setGrace]=useState('0'),[order,setOrder]=useState('0'),[bundle,setBundle]=useState('[]'),[reason,setReason]=useState(''),[message,setMessage]=useState('');
 const refresh=async()=>{if(!campaignId)return;const{data,error}=await loadOwnerDailyBenefits(campaignId);setRows(data?.rows||[]);setMessage(error?.message||'');};useEffect(()=>{refresh();},[campaignId]);
 const unsupported=useMemo(()=>{try{return JSON.parse(bundle).some(x=>x.kind==='svip')}catch{return false}},[bundle]);
 const save=async active=>{if(unsupported)return setMessage('SVIP: COMING SOON / CANNOT PUBLISH');let parsed;try{parsed=JSON.parse(bundle)}catch{return setMessage('Reward bundle JSON invalid')};const{data,error}=await saveOwnerDailyBenefit({p_id:selected?.id||null,p_campaign:campaignId,p_day_offset:Number(day),p_timezone:zone,p_reward_bundle:parsed,p_late_policy:policy,p_grace_seconds:Number(grace),p_active:active,p_sort_order:Number(order),p_reason:reason,p_request_id:id()});setMessage(error?.message||JSON.stringify(data));if(!error)refresh();};
 return <View style={s.card}><AiBackdrop opacity={.22}/><Text style={s.h}>Daily benefits</Text><ScrollView horizontal>{rows.map(x=><Pressable key={x.id} onPress={()=>{setSelected(x);setDay(String(x.day_offset));setZone(x.timezone);setPolicy(x.late_policy);setGrace(String(x.grace_seconds));setOrder(String(x.sort_order));setBundle(JSON.stringify(x.reward_bundle,null,2));}} style={s.chip}><Text style={s.t}>Day {x.day_offset+1} · {x.active?'Enabled':'Disabled'} · {x.claimed_count}/{x.claim_count}</Text></Pressable>)}</ScrollView><F l="Day offset" v={day} set={setDay}/><F l="Server timezone" v={zone} set={setZone}/><F l="Policy: same_day / grace / campaign_late / no_expiry" v={policy} set={setPolicy}/><F l="Grace seconds" v={grace} set={setGrace}/><F l="Sort order" v={order} set={setOrder}/><F l="Reward bundle JSON" v={bundle} set={setBundle} multi/><F l="Mandatory reason" v={reason} set={setReason}/>{unsupported&&<Text style={s.warn}>SVIP COMING SOON / CANNOT PUBLISH</Text>}<View style={s.row}><B t="Preview disabled" f={()=>save(false)}/><B t="Save & enable" f={()=>save(true)} disabled={unsupported}/></View><Text style={s.msg}>{message}</Text></View>}
const F=({l,v,set,multi})=><View><Text style={s.l}>{l}</Text><TextInput value={v} onChangeText={set} multiline={multi} style={[s.i,multi&&{height:100}]}/></View>;const B=({t,f,disabled})=><Pressable disabled={disabled} onPress={f} style={[s.b,disabled&&{opacity:.35}]}><Text style={s.bt}>{t}</Text></Pressable>;const s=StyleSheet.create({card:{padding:12,backgroundColor:'#10182d',borderRadius:14,marginTop:12},h:{color:'#fff',fontSize:17,fontWeight:'900'},chip:{padding:8,margin:4,backgroundColor:'#24304c',borderRadius:9},t:{color:'#dbeafe'},l:{color:'#94a3b8',marginTop:8},i:{color:'#fff',backgroundColor:'#0b1224',padding:9,borderRadius:8},row:{flexDirection:'row',flexWrap:'wrap'},b:{backgroundColor:'#6d28d9',padding:10,borderRadius:8,margin:4},bt:{color:'#fff',fontWeight:'800'},warn:{color:'#fbbf24',marginTop:8},msg:{color:'#67e8f9',marginTop:8}});

