import {HomeAIText as Text} from './HomeAIChrome';
import TextInput from './DraftTextInput';
import {AiPressable as Pressable,AiBackdrop} from './AiChrome';
import React,{useEffect,useState} from 'react';
import {StyleSheet,View} from 'react-native';
import {supabase} from '../lib/supabase';
import {OwnerWithdrawalHistory} from './OwnerAuditHistory';
import { PREMIUM } from './designSystem';
const C={panel:PREMIUM.colors.panel,panel2:PREMIUM.colors.panelSoft,line:PREMIUM.colors.line,text:PREMIUM.colors.text,muted:PREMIUM.colors.muted,purple:PREMIUM.colors.violet,gold:PREMIUM.colors.gold,green:PREMIUM.colors.green};
export default function OwnerSettlementDesk({onNotice}){
 const [policy,setPolicy]=useState({mode:'enabled',enabled:true,merchant_enabled:true,official_enabled:false,allow_diamonds:true,allow_seller_balance:true}),[min,setMin]=useState('1000'),[max,setMax]=useState('1000000000'),[busy,setBusy]=useState(false);
 const refresh=async()=>{const {data,error}=await supabase.rpc('load_withdrawal_policy');if(error)return onNotice?.(error.message);setPolicy(data||{});setMin(String(data?.min_units||1000));setMax(String(data?.max_units||1000000000));};
 useEffect(()=>{refresh()},[]);
 const save=async()=>{const lo=Number(min),hi=Number(max);if(!Number.isSafeInteger(lo)||!Number.isSafeInteger(hi)||lo<1||hi<lo)return onNotice?.('Invalid withdrawal min/max');setBusy(true);const {data,error}=await supabase.rpc('owner_update_withdrawal_policy',{p_mode:policy.mode||'enabled',p_min_units:lo,p_max_units:hi,p_allow_diamonds:policy.allow_diamonds!==false,p_allow_seller:policy.allow_seller_balance!==false,p_official_enabled:policy.official_enabled===true,p_merchant_enabled:policy.merchant_enabled!==false});setBusy(false);if(error)return onNotice?.(error.message);setPolicy(data||policy);onNotice?.('Withdrawal policy updated');};
 const chooseMode=mode=>setPolicy(p=>({...p,mode,enabled:mode==='enabled'}));
 return <View style={s.wrap}><AiBackdrop opacity={.22}/><Text style={s.title}>Merchant withdrawal control</Text><Text style={s.help}>Merchant route and Company / Owner route stay separate. Company requests use the existing protected Owner queue.</Text><View style={s.modes}>{[['enabled','ON'],['coming_soon','COMING SOON'],['off','OFF']].map(([k,l])=><Pressable key={k} onPress={()=>chooseMode(k)} style={[s.mode,policy.mode===k&&s.modeOn]}><Text style={s.modeText}>{l}</Text></Pressable>)}</View><View style={s.modes}>{[['allow_diamonds','DIAMONDS'],['allow_seller_balance','SELLER']].map(([k,l])=><Pressable key={k} onPress={()=>setPolicy(p=>({...p,[k]:!p[k]}))} style={[s.mode,policy[k]&&s.allowOn]}><Text style={s.modeText}>{l}: {policy[k]?'ON':'OFF'}</Text></Pressable>)}</View><View style={s.modes}><Pressable onPress={()=>setPolicy(p=>({...p,merchant_enabled:p.merchant_enabled===false}))} style={[s.mode,policy.merchant_enabled!==false&&s.allowOn]}><Text style={s.modeText}>WITHDRAWAL → MERCHANT: {policy.merchant_enabled!==false?'ON':'OFF'}</Text></Pressable><Pressable onPress={()=>setPolicy(p=>({...p,official_enabled:p.official_enabled!==true}))} style={[s.mode,policy.official_enabled===true&&s.allowOn]}><Text style={s.modeText}>WITHDRAWAL → OFFICIAL / COMPANY: {policy.official_enabled===true?'ON':'OFF'}</Text></Pressable></View><View style={s.minmax}><TextInput value={min} onChangeText={setMin} keyboardType="number-pad" placeholder="Minimum" placeholderTextColor="#737B8E" style={[s.input,s.flex]}/><TextInput value={max} onChangeText={setMax} keyboardType="number-pad" placeholder="Maximum" placeholderTextColor="#737B8E" style={[s.input,s.flex]}/></View><Pressable disabled={busy} onPress={save} style={s.save}><Text style={s.saveText}>{busy?'SAVING…':'SAVE WITHDRAWAL POLICY'}</Text></Pressable><OwnerWithdrawalHistory onNotice={onNotice}/></View>;
}
const s=StyleSheet.create({wrap:{marginTop:12,borderRadius:19,backgroundColor:'#10141E',borderWidth:1,borderColor:'#684974',padding:11},title:{color:C.text,fontSize:16,fontWeight:'900'},help:{color:C.muted,fontSize:8,lineHeight:14,marginTop:4},modes:{flexDirection:'row',gap:6,marginTop:8},mode:{flex:1,minHeight:38,borderRadius:10,backgroundColor:'#281B35',borderWidth:1,borderColor:'#684974',alignItems:'center',justifyContent:'center'},modeOn:{backgroundColor:'#5039BB',borderColor:C.gold},allowOn:{backgroundColor:'#17392D',borderColor:C.green},modeText:{color:C.text,fontSize:7,fontWeight:'900',textAlign:'center'},minmax:{flexDirection:'row',gap:6},flex:{flex:1},input:{minHeight:42,borderRadius:11,backgroundColor:'#0D1019',borderWidth:1,borderColor:'#684974',color:C.text,paddingHorizontal:10,marginTop:7},save:{minHeight:42,borderRadius:11,backgroundColor:'#67407C',alignItems:'center',justifyContent:'center',marginTop:7},saveText:{color:'#fff',fontSize:7,fontWeight:'900'}});
