import {HomeAIText as Text} from './HomeAIChrome';
import {AiPressable as Pressable,AiBackdrop} from './AiChrome';
import React,{useCallback,useEffect,useState} from 'react';
import {Alert,StyleSheet,View} from 'react-native';
import {supabase} from '../lib/supabase';
import { PREMIUM } from './designSystem';
const C={panel:PREMIUM.colors.panel,panel2:PREMIUM.colors.panelSoft,line:PREMIUM.colors.line,text:PREMIUM.colors.text,muted:PREMIUM.colors.muted,purple:PREMIUM.colors.violet,cyan:PREMIUM.colors.cyan,gold:PREMIUM.colors.gold,danger:PREMIUM.colors.rose,green:PREMIUM.colors.green};
export default function OwnerModerationCenter(){
 const [rows,setRows]=useState([]),[filter,setFilter]=useState('open'),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[locked,setLocked]=useState(false);
 const refresh=useCallback(async(f=filter)=>{const {data,error}=await supabase.rpc('owner_moderation_queue',{p_status:f,p_limit:150});if(error){setLocked(true);return;}setLocked(false);setRows(data||[]);},[filter]);useEffect(()=>{refresh()},[refresh]);
 if(locked)return null;
 const resolve=async(row,resolution)=>{setBusy(true);const {error}=await supabase.rpc('owner_resolve_report',{p_report:row.id,p_resolution:resolution,p_note:`Owner moderation: ${resolution}`});setBusy(false);if(error)return Alert.alert('Moderation',error.message);await refresh();};
 return <View style={s.wrap}><AiBackdrop opacity={.22}/><Pressable onPress={()=>setOpen(x=>!x)} style={s.head}><View><Text style={s.title}>Moderation Queue</Text><Text style={s.meta}>{rows.length} {filter} reports • audited</Text></View><Text style={s.arrow}>{open?'▲':'▼'}</Text></Pressable>{open?<><View style={s.filters}>{['open','in_review','resolved','dismissed','all'].map(x=><Pressable key={x} onPress={()=>{setFilter(x);refresh(x)}} style={[s.filter,filter===x&&s.filterOn]}><Text style={s.filterText}>{x.replace('_',' ').toUpperCase()}</Text></Pressable>)}</View>{rows.map(r=><View key={r.id} style={s.row}><View style={s.flex}><Text style={s.rowTitle}>{String(r.target_type).toUpperCase()} • {r.target_id}</Text><Text style={s.reason}>{r.reason}</Text><Text style={s.meta}>Reported by {r.reporter_name} • ID {r.reporter_public_id} • {new Date(r.created_at).toLocaleString()}</Text>{r.details?<Text style={s.detail}>{r.details}</Text>:null}</View>{['open','in_review'].includes(r.status)?<View style={s.actions}><Pressable disabled={busy} onPress={()=>resolve(r,'resolved')} style={s.ok}><Text style={s.okText}>RESOLVE</Text></Pressable><Pressable disabled={busy} onPress={()=>resolve(r,'dismissed')} style={s.no}><Text style={s.noText}>DISMISS</Text></Pressable></View>:<Text style={s.status}>{String(r.status).toUpperCase()}</Text>}</View>)}</>:null}</View>;
}
const s=StyleSheet.create({wrap:{backgroundColor:'#10141E',borderWidth:1,borderColor:'#684974',borderRadius:19,padding:10,marginTop:12},head:{minHeight:47,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},title:{color:C.text,fontSize:15,fontWeight:'900'},meta:{color:C.muted,fontSize:7,lineHeight:12,marginTop:3},arrow:{color:C.gold,fontSize:9,fontWeight:'900'},filters:{flexDirection:'row',flexWrap:'wrap',gap:5,marginVertical:7},filter:{minHeight:31,borderRadius:9,backgroundColor:'#281B35',paddingHorizontal:8,alignItems:'center',justifyContent:'center'},filterOn:{backgroundColor:'#4E38B8',borderWidth:1,borderColor:C.gold},filterText:{color:C.text,fontSize:6,fontWeight:'900'},row:{minHeight:80,borderTopWidth:1,borderTopColor:'#684974',paddingVertical:9,flexDirection:'row',alignItems:'center',gap:7},flex:{flex:1},rowTitle:{color:C.text,fontSize:9,fontWeight:'900'},reason:{color:C.gold,fontSize:8,fontWeight:'800',marginTop:3},detail:{color:'#BBC2D0',fontSize:7,lineHeight:12,marginTop:3},actions:{gap:5},ok:{minWidth:55,minHeight:31,borderRadius:9,backgroundColor:'#17392D',alignItems:'center',justifyContent:'center'},okText:{color:C.green,fontSize:6,fontWeight:'900'},no:{minWidth:55,minHeight:31,borderRadius:9,backgroundColor:'#3A1E29',alignItems:'center',justifyContent:'center'},noText:{color:C.danger,fontSize:6,fontWeight:'900'},status:{color:C.cyan,fontSize:6,fontWeight:'900'}});

