import {HomeAIText as Text} from './HomeAIChrome';
import TextInput from './DraftTextInput';
import {AiPressable as Pressable,AiBackdrop} from './AiChrome';
import React,{useCallback,useEffect,useState} from 'react';
import {Alert,ScrollView,StyleSheet,View} from 'react-native';
import {supabase} from '../lib/supabase';
import {PREMIUM} from './designSystem';

const C=PREMIUM.colors;
const TABS=['Wallet freeze','Incidents','Deletion'];
export default function OwnerSafetyCenter(){
 const [tab,setTab]=useState('Wallet freeze');
 return <View style={s.wrap}><AiBackdrop opacity={.22}/><Text style={s.kicker}>OWNER + CO-OWNER CONTINUITY</Text><Text style={s.title}>Safety & Recovery</Text><Text style={s.help}>Use the narrowest action possible. Wallet freeze does not ban login; deletion keeps a cooling period; incidents preserve recovery history.</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.tabs}>{TABS.map(x=><Pressable key={x} onPress={()=>setTab(x)} style={[s.tab,tab===x&&s.tabOn]}><Text style={s.tabText}>{x.toUpperCase()}</Text></Pressable>)}</ScrollView>{tab==='Wallet freeze'?<Wallet/>:tab==='Incidents'?<Incidents/>:<Deletion/>}</View>;
}

function Wallet(){
 const [id,setId]=useState(''),[hours,setHours]=useState('24'),[reason,setReason]=useState('Wallet activity under review'),[rows,setRows]=useState([]),[busy,setBusy]=useState(false);
 const refresh=useCallback(async()=>{const {data,error}=await supabase.rpc('owner_wallet_freezes');if(error)return;setRows(data||[])},[]);useEffect(()=>{refresh()},[refresh]);
 const run=active=>{if(!/^\d{6,}$/.test(id.trim()))return Alert.alert('Permanent ID','Enter a valid user ID.');Alert.alert(active?'Freeze wallet spending?':'Restore wallet spending?',`ID ${id}\nIncoming credits and login remain available.`,[{text:'Cancel',style:'cancel'},{text:'CONFIRM',style:active?'destructive':'default',onPress:async()=>{setBusy(true);const {error}=await supabase.rpc('owner_set_wallet_freeze',{p_public_id:Number(id),p_active:active,p_duration_hours:active&&hours?Number(hours):null,p_reason:reason.trim()});setBusy(false);if(error)return Alert.alert('Wallet safety',error.message);setId('');await refresh();}}])};
 return <View><View style={s.card}><AiBackdrop opacity={.22}/><TextInput value={id} onChangeText={x=>setId(x.replace(/\D/g,''))} keyboardType="number-pad" placeholder="Permanent user ID" placeholderTextColor="#747E93" style={s.input}/><TextInput value={hours} onChangeText={x=>setHours(x.replace(/\D/g,''))} keyboardType="number-pad" placeholder="Hours; empty = permanent" placeholderTextColor="#747E93" style={s.input}/><TextInput value={reason} onChangeText={setReason} placeholder="Required reason" placeholderTextColor="#747E93" style={s.input}/><View style={s.actions}><Action disabled={busy} danger label="FREEZE SPEND" onPress={()=>run(true)}/><Action disabled={busy} label="RESTORE" onPress={()=>run(false)}/></View></View>{rows.map(r=><View key={r.id} style={s.item}><View style={s.flex}><Text style={s.itemTitle}>{r.display_name} • ID {r.public_id}</Text><Text style={s.meta}>{r.reason}{r.expires_at?` • until ${new Date(r.expires_at).toLocaleString()}`:''}</Text></View><Text style={[s.state,{color:r.active?C.rose:C.green}]}>{r.active?'FROZEN':'CLEAR'}</Text></View>)}</View>;
}

function Incidents(){
 const [severity,setSeverity]=useState('medium'),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[rows,setRows]=useState([]),[busy,setBusy]=useState(false);
 const refresh=useCallback(async()=>{const {data}=await supabase.rpc('owner_incident_cases');setRows(data||[])},[]);useEffect(()=>{refresh()},[refresh]);
 const create=async()=>{if(title.trim().length<3||description.trim().length<3)return Alert.alert('Incident','Title and description are required.');setBusy(true);const {error}=await supabase.rpc('owner_create_incident',{p_type:'system',p_severity:severity,p_title:title.trim(),p_description:description.trim(),p_scope:{}});setBusy(false);if(error)return Alert.alert('Incident',error.message);setTitle('');setDescription('');await refresh();};
 const setStatus=async(row,status)=>{setBusy(true);const {error}=await supabase.rpc('owner_update_incident',{p_incident:row.id,p_status:status,p_note:`Status changed to ${status}`});setBusy(false);if(error)return Alert.alert('Incident',error.message);await refresh();};
 return <View><View style={s.card}><AiBackdrop opacity={.22}/><View style={s.chips}>{['low','medium','high','critical'].map(x=><Pressable key={x} onPress={()=>setSeverity(x)} style={[s.chip,severity===x&&s.chipOn]}><Text style={s.chipText}>{x.toUpperCase()}</Text></Pressable>)}</View><TextInput value={title} onChangeText={setTitle} placeholder="Incident title" placeholderTextColor="#747E93" style={s.input}/><TextInput value={description} onChangeText={setDescription} multiline placeholder="What happened / recovery needed" placeholderTextColor="#747E93" style={[s.input,{minHeight:80,textAlignVertical:'top'}]}/><Action disabled={busy} label="CREATE INCIDENT" onPress={create}/></View>{rows.map(r=><View key={r.id} style={s.itemColumn}><View style={s.row}><View style={s.flex}><Text style={s.itemTitle}>{r.title}</Text><Text style={s.meta}>{String(r.severity).toUpperCase()} • {String(r.status).toUpperCase()}</Text></View></View><Text style={s.desc}>{r.description}</Text>{!['resolved','closed'].includes(r.status)?<View style={s.actions}><Action disabled={busy} label="INVESTIGATE" onPress={()=>setStatus(r,'investigating')}/><Action disabled={busy} label="RESOLVE" onPress={()=>setStatus(r,'resolved')}/></View>:null}</View>)}</View>;
}

function Deletion(){
 const [rows,setRows]=useState([]),[busy,setBusy]=useState(false);const refresh=useCallback(async()=>{const {data}=await supabase.rpc('owner_account_deletion_requests',{p_status:'open'});setRows(data||[])},[]);useEffect(()=>{refresh()},[refresh]);
 const act=async(row,action)=>{setBusy(true);const {error}=await supabase.rpc('owner_review_account_deletion',{p_request:row.id,p_action:action,p_note:`Owner review: ${action}`});setBusy(false);if(error)return Alert.alert('Deletion review',error.message);await refresh();};
 return <View>{rows.map(row=><View key={row.id} style={s.itemColumn}><Text style={s.itemTitle}>{row.display_name} • ID {row.public_id}</Text><Text style={s.meta}>{String(row.status).toUpperCase()} • requested {new Date(row.requested_at).toLocaleDateString()}</Text><Text style={s.desc}>{row.reason}</Text><Text style={s.cooling}>Cooling until {new Date(row.cooling_until).toLocaleString()}</Text><View style={s.actions}>{row.status==='pending'?<Action disabled={busy} label="VERIFY" onPress={()=>act(row,'verify')}/>:null}<Action disabled={busy} label="SCHEDULE" onPress={()=>act(row,'schedule')}/><Action disabled={busy} danger label="REJECT" onPress={()=>act(row,'reject')}/></View></View>)}{!rows.length?<View style={s.empty}><Text style={s.meta}>No open deletion requests.</Text></View>:null}</View>;
}

function Action({label,onPress,danger,disabled}){return <Pressable disabled={disabled} onPress={onPress} style={[s.action,danger?s.actionDanger:s.actionSafe]}><Text style={[s.actionText,{color:danger?C.rose:C.green}]}>{label}</Text></Pressable>}
const s=StyleSheet.create({wrap:{marginTop:12,borderRadius:22,backgroundColor:'#0E121B',borderWidth:1,borderColor:'#684974',padding:12},kicker:{color:C.cyan,fontSize:7,fontWeight:'900',letterSpacing:1.2},title:{color:C.text,fontSize:17,fontWeight:'900',marginTop:4},help:{color:C.muted,fontSize:8,lineHeight:13,marginTop:4},tabs:{gap:6,paddingVertical:10},tab:{minWidth:100,minHeight:38,borderRadius:12,backgroundColor:C.panelSoft,borderWidth:1,borderColor:'#684974',alignItems:'center',justifyContent:'center',paddingHorizontal:9},tabOn:{backgroundColor:C.violetDeep,borderColor:C.gold},tabText:{color:C.text,fontSize:7,fontWeight:'900'},card:{borderRadius:17,backgroundColor:'#180F25',borderWidth:1,borderColor:'#684974',padding:10},input:{minHeight:43,borderRadius:12,backgroundColor:'#0D1019',borderWidth:1,borderColor:'#30384C',color:C.text,paddingHorizontal:10,marginTop:7,fontSize:10},actions:{flexDirection:'row',gap:6,marginTop:8},action:{flex:1,minHeight:36,borderRadius:10,alignItems:'center',justifyContent:'center',paddingHorizontal:5},actionSafe:{backgroundColor:'#17382D'},actionDanger:{backgroundColor:'#3D1E29'},actionText:{fontSize:7,fontWeight:'900'},item:{minHeight:66,borderRadius:16,backgroundColor:'#180F25',borderWidth:1,borderColor:'#684974',padding:9,marginTop:7,flexDirection:'row',alignItems:'center',gap:8},itemColumn:{borderRadius:17,backgroundColor:'#180F25',borderWidth:1,borderColor:'#684974',padding:10,marginTop:7},row:{flexDirection:'row',alignItems:'center'},flex:{flex:1},itemTitle:{color:C.text,fontSize:10,fontWeight:'900'},meta:{color:C.muted,fontSize:7,lineHeight:12,marginTop:4},state:{fontSize:7,fontWeight:'900'},desc:{color:C.textSoft,fontSize:8,lineHeight:13,marginTop:7},cooling:{color:C.gold,fontSize:7,fontWeight:'800',marginTop:6},chips:{flexDirection:'row',gap:5,flexWrap:'wrap'},chip:{minHeight:31,borderRadius:9,backgroundColor:C.panelSoft,paddingHorizontal:8,alignItems:'center',justifyContent:'center'},chipOn:{backgroundColor:C.violetDeep,borderWidth:1,borderColor:C.gold},chipText:{color:C.text,fontSize:6,fontWeight:'900'},empty:{padding:26,alignItems:'center'}});

