import {HomeAIText as Text} from './HomeAIChrome';
import {AiPressable as Pressable,AiBackdrop} from './AiChrome';
import React,{useEffect,useMemo,useRef,useState} from 'react';
import {StyleSheet,View} from 'react-native';
import {supabase} from '../lib/supabase';
import { PREMIUM } from './designSystem';
const C={panel:PREMIUM.colors.panel,panel2:PREMIUM.colors.panelSoft,line:PREMIUM.colors.line,text:PREMIUM.colors.text,muted:PREMIUM.colors.muted,purple:PREMIUM.colors.violet,cyan:PREMIUM.colors.cyan,gold:PREMIUM.colors.gold,danger:PREMIUM.colors.rose,green:PREMIUM.colors.green};
const n=v=>Number(v||0).toLocaleString();
const when=v=>v?new Date(v).toLocaleString():'—';
export function OwnerFinanceActivityHistory({onNotice,refreshKey=0}){
 const [rows,setRows]=useState([]),[filter,setFilter]=useState('all'),[open,setOpen]=useState(false),[busy,setBusy]=useState(false);
 const epoch=useRef(0),alive=useRef(true);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;++epoch.current;}},[]);
 const load=async(next=filter)=>{const token=++epoch.current;setBusy(true);setRows([]);try{const {data,error}=await supabase.rpc('owner_finance_activity_report',{p_asset:next,p_limit:200});if(!alive.current||token!==epoch.current)return;if(error)throw error;setRows(data||[]);}catch(error){if(alive.current&&token===epoch.current)onNotice?.(error.message||'Could not load finance history');}finally{if(alive.current&&token===epoch.current)setBusy(false);}};
 useEffect(()=>{if(open)load()},[open,refreshKey]);
 const shown=useMemo(()=>rows.slice(0,200),[rows]);
 return <View style={s.wrap}><AiBackdrop opacity={.22}/><Pressable onPress={()=>setOpen(x=>!x)} style={s.header}><View style={s.flex}><Text style={s.title}>Owner / merchant / seller history</Text><Text style={s.help}>Real records from the canonical wallet ledger • all recipient IDs</Text></View><Text style={s.chev}>{open?'⌃':'⌄'}</Text></Pressable>{open?<><View style={s.filters}>{['all','coins','diamonds'].map(x=><Pressable key={x} onPress={()=>{setFilter(x);load(x)}} style={[s.filter,filter===x&&s.filterOn]}><Text style={s.filterText}>{x.toUpperCase()}</Text></Pressable>)}<Pressable disabled={busy} onPress={()=>load()} style={s.refresh}><Text style={s.refreshText}>{busy?'…':'REFRESH'}</Text></Pressable></View>{shown.map(r=>{const positive=Number(r.amount)>=0;return <View key={r.event_id} style={s.row}><View style={[s.icon,positive?s.in:s.out]}><Text style={s.iconText}>{positive?'＋':'−'}</Text></View><View style={s.flex}><Text style={s.rowTitle}>{String(r.asset).toUpperCase()} • {r.target_name} • ID {r.target_public_id}</Text><Text style={s.meta}>{r.note||'Owner finance adjustment'}</Text><Text style={s.meta}>By {r.actor_name||'System'}{r.actor_public_id?' • ID '+r.actor_public_id:''} • {when(r.created_at)}</Text><Text style={s.ref}>REF {r.reference_id||r.event_id}</Text></View><Text style={[s.amount,{color:positive?C.green:C.danger}]}>{positive?'+':''}{n(r.amount)} {r.asset==='diamonds'?'◆':'🪙'}</Text></View>})}{!busy&&!shown.length?<Text style={s.empty}>No recharge or Owner adjustment recorded yet.</Text>:null}</>:null}</View>;
}
export function OwnerWithdrawalHistory({onNotice,refreshKey=0}){
 const [rows,setRows]=useState([]),[filter,setFilter]=useState('all'),[open,setOpen]=useState(false),[busy,setBusy]=useState(false);
 const load=async(next=filter)=>{setBusy(true);const {data,error}=await supabase.rpc('owner_withdrawal_history',{p_status:next,p_limit:200});setBusy(false);if(error)return onNotice?.(error.message);setRows(data||[]);};
 useEffect(()=>{if(open)load()},[open,refreshKey]);
 return <View style={s.wrap}><AiBackdrop opacity={.22}/><Pressable onPress={()=>setOpen(x=>!x)} style={s.header}><View style={s.flex}><Text style={s.title}>Merchant withdrawal records</Text><Text style={s.help}>Requests, route, reviewer, status and payment reference</Text></View><Text style={s.chev}>{open?'⌃':'⌄'}</Text></Pressable>{open?<><View style={s.filters}>{['all','pending','approved','paid','rejected','cancelled'].map(x=><Pressable key={x} onPress={()=>{setFilter(x);load(x)}} style={[s.filter,filter===x&&s.filterOn]}><Text style={s.filterText}>{x.toUpperCase()}</Text></Pressable>)}<Pressable disabled={busy} onPress={()=>load()} style={s.refresh}><Text style={s.refreshText}>{busy?'…':'REFRESH'}</Text></Pressable></View>{rows.map(r=><View key={r.request_id} style={s.row}><View style={s.flex}><Text style={s.rowTitle}>{String(r.source_account).replaceAll('_',' ').toUpperCase()} • {n(r.amount_units)}</Text><Text style={s.meta}>{r.user_name} • ID {r.user_public_id} • {String(r.processing_route).toUpperCase()}</Text><Text style={s.meta}>{String(r.status).toUpperCase()} • requested {when(r.created_at)}</Text>{r.merchant_public_id?<Text style={s.meta}>Merchant {r.merchant_name} • ID {r.merchant_public_id}</Text>:null}{r.reviewer_public_id?<Text style={s.meta}>Reviewed by {r.reviewer_name} • ID {r.reviewer_public_id} • {when(r.reviewed_at)}</Text>:null}{r.external_reference?<Text style={s.ref}>PAYMENT REF {r.external_reference}</Text>:null}{r.request_note?<Text style={s.meta}>Request: {r.request_note}</Text>:null}{r.review_note?<Text style={s.meta}>Review: {r.review_note}</Text>:null}</View><Text style={s.status}>{String(r.status).toUpperCase()}</Text></View>)}{!busy&&!rows.length?<Text style={s.empty}>No withdrawal request recorded yet.</Text>:null}</>:null}</View>;
}
const s=StyleSheet.create({wrap:{marginTop:10,borderRadius:16,backgroundColor:'#10141E',borderWidth:1,borderColor:'#684974',overflow:'hidden'},header:{minHeight:58,padding:11,flexDirection:'row',alignItems:'center'},flex:{flex:1},title:{color:C.text,fontSize:12,fontWeight:'900'},help:{color:C.muted,fontSize:8,lineHeight:12,marginTop:3},chev:{color:C.cyan,fontSize:20,fontWeight:'900'},filters:{flexDirection:'row',flexWrap:'wrap',gap:5,paddingHorizontal:9,paddingBottom:7},filter:{borderRadius:999,backgroundColor:'#281B35',paddingHorizontal:8,paddingVertical:7},filterOn:{backgroundColor:'#5039BB',borderWidth:1,borderColor:C.gold},filterText:{color:C.text,fontSize:6,fontWeight:'900'},refresh:{borderRadius:999,backgroundColor:'#18313A',paddingHorizontal:9,paddingVertical:7},refreshText:{color:C.cyan,fontSize:6,fontWeight:'900'},row:{minHeight:78,borderTopWidth:1,borderTopColor:'#684974',padding:9,flexDirection:'row',alignItems:'center',gap:7},icon:{width:30,height:30,borderRadius:10,alignItems:'center',justifyContent:'center'},in:{backgroundColor:'#17392D'},out:{backgroundColor:'#3A1E29'},iconText:{color:'#fff',fontSize:15,fontWeight:'900'},rowTitle:{color:C.text,fontSize:9,fontWeight:'900'},meta:{color:C.muted,fontSize:7,lineHeight:11,marginTop:2},ref:{color:C.cyan,fontSize:6,lineHeight:10,marginTop:2},amount:{fontSize:8,fontWeight:'900',maxWidth:100,textAlign:'right'},status:{color:C.gold,fontSize:7,fontWeight:'900'},empty:{color:C.muted,fontSize:8,textAlign:'center',padding:18,borderTopWidth:1,borderTopColor:'#684974'}});

