import {makeRequestId} from './requestId';
import {HomeAIText as Text} from './HomeAIChrome';
import TextInput from './DraftTextInput';
import {AiPressable as Pressable,AiBackdrop} from './AiChrome';
import React,{useState} from 'react';
import {ScrollView,StyleSheet,View} from 'react-native';
import {loadOwnerRewardOperationHistory,ownerGrantRewardV2,ownerReverseReward,prepareOwnerOperation} from './rechargeRewards';
import OwnerCampaignRewardsCenter from './OwnerCampaignRewardsCenter';
import OwnerVanityIdScreen from './OwnerVanityIdScreen';
import OwnerDailyCoinGrantCenter from './OwnerDailyCoinGrantCenter';
const uuid=()=>makeRequestId();
export default function OwnerRewardOperationsCenter(){const[publicId,setPublicId]=useState(''),[kind,setKind]=useState('coins'),[code,setCode]=useState(''),[quantity,setQuantity]=useState('1'),[days,setDays]=useState(''),[reason,setReason]=useState(''),[token,setToken]=useState(''),[preview,setPreview]=useState(null),[result,setResult]=useState(''),[grantId,setGrantId]=useState(''),[history,setHistory]=useState([]),[reversePreview,setReversePreview]=useState(null);
 const prepare=async()=>{if(kind==='svip')return setResult('SVIP COMING SOON — manual grant disabled');const request=uuid();const{data,error}=await prepareOwnerOperation({p_operation_type:kind==='vanity_id'?'vanity.assign':'reward.grant',p_scope_type:'single',p_target_public_ids:[Number(publicId)],p_reason:reason,p_request_id:request,p_confirmation_token:token||null,p_expires_at:new Date(Date.now()+900000).toISOString()});setPreview(error?null:{...data,confirmationToken:token});setResult(error?.message||JSON.stringify(data));};
 const grant=async()=>{if(kind==='svip')return setResult('SVIP COMING SOON — manual grant disabled');if(!preview)return setResult('Preview is mandatory');const{data,error}=await ownerGrantRewardV2({p_operation_id:preview.operation_id,p_public_id:Number(publicId),p_kind:kind,p_code:code||null,p_quantity:Number(quantity),p_duration_seconds:days?Number(days)*86400:null,p_permanent:!days,p_reason:reason,p_request_id:uuid(),p_confirmation_token:preview.confirmationToken||null});setResult(error?.message||JSON.stringify(data));if(!error){setGrantId(data.grant_id);setPreview(null);}};
 const prepareReverse=async()=>{const r=await prepareOwnerOperation({p_operation_type:'reward.reverse',p_scope_type:'single',p_target_public_ids:[Number(publicId)],p_reason:reason,p_request_id:uuid(),p_confirmation_token:token||null,p_expires_at:new Date(Date.now()+900000).toISOString()});setReversePreview(r.error?null:r.data);setResult(r.error?.message||JSON.stringify(r.data));};
 const reverse=async()=>{if(!reversePreview)return setResult('Reversal preview required');const r=await ownerReverseReward({p_grant:grantId,p_operation_id:reversePreview.operation_id,p_reason:reason,p_request_id:uuid()});setResult(r.error?.message||JSON.stringify(r.data));if(!r.error)setReversePreview(null);};
 const loadHistory=async()=>{const r=await loadOwnerRewardOperationHistory();setHistory(r.data||[]);setResult(r.error?.message||'');};
 return <ScrollView style={s.root}><Text style={s.h}>Manual canonical reward grant</Text><Field label="Target permanent public ID" v={publicId} set={setPublicId}/><Field label="Kind (coins, diamonds, cosmetic, vip, vanity_id)" v={kind} set={setKind}/><Field label="Catalogue code / Vanity ID" v={code} set={setCode}/><Field label="Quantity / VIP prestige points" v={quantity} set={setQuantity}/><Field label="Duration days (blank permanent)" v={days} set={setDays}/><Field label="Mandatory reason" v={reason} set={setReason}/><Field label="Confirmation token" v={token} set={setToken}/><View style={s.row}><Btn t="1. Preview protected target" onPress={prepare}/><Btn t="2. Confirm canonical grant" onPress={grant} disabled={kind==='svip'}/></View><Text style={s.warn}>SVIP COMING SOON — disabled. Permanent public ID is never changed.</Text><Field label="Canonical grant ID for Founder reversal" v={grantId} set={setGrantId}/><View style={s.row}><Btn t="Preview reversal" onPress={prepareReverse}/><Btn t="Execute reversal" onPress={reverse} disabled={!reversePreview}/><Btn t="Operation history" onPress={loadHistory}/></View>{history.map(x=><Text key={x.id} style={s.history}>{x.operation_type} · {x.status} · operation {x.id} · canonical {x.result?.canonical_id||x.result?.grant_id||'—'} · reversal {x.reversal?.eligibility_status||'n/a'}</Text>)}<Text style={s.result}>{result}</Text><OwnerDailyCoinGrantCenter/><OwnerVanityIdScreen/><OwnerCampaignRewardsCenter/></ScrollView>}
const Field=({label,v,set})=><View><Text style={s.label}>{label}</Text><TextInput value={v} onChangeText={set} style={s.input}/></View>;const Btn=({t,onPress,disabled})=><Pressable disabled={disabled} onPress={onPress} style={[s.btn,disabled&&{opacity:.35}]}><Text style={s.bt}>{t}</Text></Pressable>;
const s=StyleSheet.create({root:{backgroundColor:'#080d1c',padding:14},h:{color:'#fff',fontSize:19,fontWeight:'900'},label:{color:'#cbd5e1',marginTop:10},input:{color:'#fff',backgroundColor:'#111a33',borderWidth:1,borderColor:'#334155',borderRadius:10,padding:10},row:{flexDirection:'row',flexWrap:'wrap',marginTop:12},btn:{backgroundColor:'#7c3aed',padding:11,borderRadius:10,margin:4},bt:{color:'#fff',fontWeight:'900'},warn:{color:'#fbbf24',marginTop:10},history:{color:'#cbd5e1',marginTop:5},result:{color:'#67e8f9',marginTop:10}});


