import {makeRequestId} from './requestId';
import {HomeAIText as Text} from './HomeAIChrome';
import TextInput from './DraftTextInput';
import {AiPressable as Pressable,AiBackdrop} from './AiChrome';
import React,{useEffect,useState} from 'react';
import {ScrollView,StyleSheet,View} from 'react-native';
import {loadOwnerBanners,saveCampaignBanner,setCampaignBannerState} from './rechargeRewards';
const id=()=>makeRequestId();
export default function OwnerBannerManagementScreen({campaignId}){const[rows,setRows]=useState([]),[selected,setSelected]=useState(null),[title,setTitle]=useState(''),[image,setImage]=useState(''),[fallback,setFallback]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[priority,setPriority]=useState('0'),[audience,setAudience]=useState('{}'),[reason,setReason]=useState(''),[message,setMessage]=useState('');const load=async()=>{const r=await loadOwnerBanners({p_states:null,p_limit:50,p_offset:0});setRows(r.data?.rows||[]);setMessage(r.error?.message||'');};useEffect(()=>{load();},[]);const save=async()=>{let target;try{target=JSON.parse(audience)}catch{return setMessage('Audience JSON invalid')};const r=await saveCampaignBanner({p_id:selected?.id||null,p_payload:{campaign_id:campaignId,title,image_url:image,fallback_image_url:fallback||null,deep_link:'funnyroom://recharge-rewards',active:false,starts_at:start,ends_at:end,priority:Number(priority),audience:target},p_reason:reason,p_request_id:id()});setMessage(r.error?.message||JSON.stringify(r.data));if(!r.error)load();};const state=async op=>{const r=await setCampaignBannerState({p_banner:selected?.id,p_operation:op,p_reason:reason,p_request_id:id()});setMessage(r.error?.message||JSON.stringify(r.data));if(!r.error)load();};return <View style={s.card}><AiBackdrop opacity={.22}/><Text style={s.h}>Banner remote configuration</Text><ScrollView horizontal>{rows.map(x=><Pressable key={x.id} onPress={()=>{setSelected(x);setTitle(x.title);setImage(x.image_url);setFallback(x.fallback_image_url||'');setStart(x.starts_at);setEnd(x.ends_at);setPriority(String(x.priority));setAudience(JSON.stringify(x.audience));}} style={s.chip}><Text style={s.t}>{x.title} · {x.derived_state}</Text></Pressable>)}</ScrollView><F l="Title" v={title} set={setTitle}/><F l="Image URL" v={image} set={setImage}/><F l="HTTPS fallback URL" v={fallback} set={setFallback}/><F l="Starts at" v={start} set={setStart}/><F l="Ends at" v={end} set={setEnd}/><F l="Priority" v={priority} set={setPriority}/><F l="Audience JSON" v={audience} set={setAudience}/><F l="Mandatory reason" v={reason} set={setReason}/><View style={s.row}><B t="Save draft / preview" f={save}/>{['activate','deactivate','archive','restore'].map(x=><B key={x} t={x} f={()=>state(x)} disabled={!selected}/>)}</View><Text style={s.msg}>{message}</Text></View>}
const F=({l,v,set})=><View><Text style={s.l}>{l}</Text><TextInput value={v} onChangeText={set} style={s.i}/></View>;const B=({t,f,disabled})=><Pressable disabled={disabled} onPress={f} style={[s.b,disabled&&{opacity:.35}]}><Text style={s.bt}>{t}</Text></Pressable>;const s=StyleSheet.create({card:{padding:12,backgroundColor:'#10182d',borderRadius:14,marginTop:12},h:{color:'#fff',fontSize:17,fontWeight:'900'},chip:{padding:8,margin:4,backgroundColor:'#24304c',borderRadius:9},t:{color:'#dbeafe'},l:{color:'#94a3b8',marginTop:8},i:{color:'#fff',backgroundColor:'#0b1224',padding:9,borderRadius:8},row:{flexDirection:'row',flexWrap:'wrap'},b:{backgroundColor:'#6d28d9',padding:10,borderRadius:8,margin:4},bt:{color:'#fff',fontWeight:'800'},msg:{color:'#67e8f9',marginTop:8}});

