import {HomeAIText as Text} from './HomeAIChrome';
import TextInput from './DraftTextInput';
import {AiPressable as Pressable,AiBackdrop} from './AiChrome';
import React,{useState} from 'react';
import {Alert,StyleSheet,View} from 'react-native';
import {supabase} from '../lib/supabase';
import { PREMIUM } from './designSystem';
const C={panel:PREMIUM.colors.panel,panel2:PREMIUM.colors.panelSoft,line:PREMIUM.colors.line,text:PREMIUM.colors.text,muted:PREMIUM.colors.muted,purple:PREMIUM.colors.violet,cyan:PREMIUM.colors.cyan,gold:PREMIUM.colors.gold,green:PREMIUM.colors.green,danger:PREMIUM.colors.rose};
const n=v=>Number(v||0).toLocaleString();
export default function OwnerSalaryDesk({onNotice}){
 const [id,setId]=useState(''),[role,setRole]=useState('host'),[period,setPeriod]=useState(new Date().toISOString().slice(0,7)),[units,setUnits]=useState('0'),[earned,setEarned]=useState('0'),[status,setStatus]=useState('open'),[rows,setRows]=useState([]),[busy,setBusy]=useState(false);
 const notify=x=>onNotice?.(x);
 const load=async()=>{if(!/^\d{4,}$/.test(id.trim()))return notify('Valid permanent ID required');setBusy(true);const {data,error}=await supabase.rpc('owner_salary_user_report',{p_public_id:Number(id)});setBusy(false);if(error)return notify(error.message);setRows(data||[]);notify(`Salary records loaded • ID ${id}`);};
 const save=async()=>{const u=Math.floor(Number(units.replaceAll(',',''))),e=Math.floor(Number(earned.replaceAll(',','')));if(!/^\d{4,}$/.test(id.trim())||!role.trim()||!period.trim()||!Number.isSafeInteger(u)||u<0||!Number.isSafeInteger(e)||e<0)return notify('Check salary ID, role, period, units and earned amount');setBusy(true);const {data,error}=await supabase.rpc('owner_set_salary_progress',{p_public_id:Number(id),p_role:role.trim().toLowerCase().replaceAll(' ','_'),p_period_key:period.trim(),p_eligible_units:u,p_earned_amount:e,p_status:status});setBusy(false);if(error)return notify(error.message);setRows(data||[]);notify(`Salary progress saved • ID ${id}`);};
 const settle=row=>Alert.alert('Settle remaining salary?',`${String(row.role_key).replaceAll('_',' ').toUpperCase()} • ${row.period_key}\nEarned ${n(row.earned_amount)}\nAdvance ${n(row.advance_used)}\nAlready settled ${n(row.settled_amount)}\nRemaining ${n(Math.max(0,Number(row.earned_amount)-Number(row.advance_used)-Number(row.settled_amount)))}`, [{text:'Cancel',style:'cancel'},{text:'SETTLE',onPress:async()=>{setBusy(true);const {data,error}=await supabase.rpc('owner_settle_salary_record',{p_salary_record:row.id,p_note:`Owner salary settlement • ID ${id}`});setBusy(false);if(error)return notify(error.message);notify(`Salary settled • ID ${data.public_id} • ${n(data.amount)} coins`);await load();}}]);
 return <View style={s.wrap}><AiBackdrop opacity={.22}/><Text style={s.title}>Salary operations</Text><Text style={s.help}>Target progress, earned salary, advance deduction and final settlement use one audited flow. Access follows your selected country, user or agency authority.</Text><TextInput value={id} onChangeText={setId} keyboardType="number-pad" placeholder="Permanent ID" placeholderTextColor="#737B8E" style={s.input}/><View style={s.row}><TextInput value={role} onChangeText={setRole} autoCapitalize="none" placeholder="Role key e.g. host / bd" placeholderTextColor="#737B8E" style={[s.input,s.flex]}/><TextInput value={period} onChangeText={setPeriod} placeholder="2026-08" placeholderTextColor="#737B8E" style={[s.input,s.period]}/></View><View style={s.row}><TextInput value={units} onChangeText={setUnits} keyboardType="number-pad" placeholder="Eligible units" placeholderTextColor="#737B8E" style={[s.input,s.flex]}/><TextInput value={earned} onChangeText={setEarned} keyboardType="number-pad" placeholder="Earned salary coins" placeholderTextColor="#737B8E" style={[s.input,s.flex]}/></View><View style={s.chips}>{['open','qualified','cancelled'].map(x=><Pressable key={x} onPress={()=>setStatus(x)} style={[s.chip,status===x&&s.chipOn]}><Text style={s.chipText}>{x.toUpperCase()}</Text></Pressable>)}</View><View style={s.actions}><Pressable disabled={busy} onPress={save} style={s.primary}><Text style={s.primaryText}>{busy?'WAIT…':'SAVE PROGRESS'}</Text></Pressable><Pressable disabled={busy} onPress={load} style={s.secondary}><Text style={s.secondaryText}>VIEW RECORD</Text></Pressable></View>{rows.map(r=><View key={r.id} style={s.record}><View style={s.flex}><Text style={s.recordTitle}>{String(r.role_key).replaceAll('_',' ').toUpperCase()} • {r.period_key}</Text><Text style={s.meta}>Units {n(r.eligible_units)} • Earned {n(r.earned_amount)} • Advance {n(r.advance_used)} • Settled {n(r.settled_amount)} • {String(r.status).toUpperCase()}</Text></View>{r.status!=='cancelled'&&Number(r.earned_amount)>Number(r.advance_used)+Number(r.settled_amount)?<Pressable onPress={()=>settle(r)} style={s.settle}><Text style={s.settleText}>SETTLE</Text></Pressable>:<Text style={s.done}>{r.status==='settled'?'PAID':'—'}</Text>}</View>)}</View>;
}
const s=StyleSheet.create({wrap:{marginTop:12,borderRadius:19,backgroundColor:'#10141E',borderWidth:1,borderColor:'#684974',padding:11},title:{color:C.text,fontSize:16,fontWeight:'900'},help:{color:C.muted,fontSize:8,lineHeight:14,marginTop:4},input:{minHeight:43,borderRadius:11,backgroundColor:'#0D1019',borderWidth:1,borderColor:'#684974',color:C.text,paddingHorizontal:10,marginTop:7},row:{flexDirection:'row',gap:6},flex:{flex:1},period:{width:96},chips:{flexDirection:'row',gap:6,marginTop:8},chip:{flex:1,minHeight:34,borderRadius:10,backgroundColor:'#281B35',alignItems:'center',justifyContent:'center'},chipOn:{backgroundColor:'#5039BB',borderWidth:1,borderColor:C.gold},chipText:{color:C.text,fontSize:7,fontWeight:'900'},actions:{flexDirection:'row',gap:7,marginTop:8},primary:{flex:1,minHeight:42,borderRadius:11,backgroundColor:'#67407C',alignItems:'center',justifyContent:'center'},primaryText:{color:'#fff',fontSize:8,fontWeight:'900'},secondary:{flex:1,minHeight:42,borderRadius:11,backgroundColor:'#281B35',alignItems:'center',justifyContent:'center'},secondaryText:{color:C.cyan,fontSize:8,fontWeight:'900'},record:{minHeight:66,borderRadius:14,backgroundColor:'#180F25',borderWidth:1,borderColor:'#684974',padding:8,marginTop:7,flexDirection:'row',alignItems:'center',gap:7},recordTitle:{color:C.text,fontSize:9,fontWeight:'900'},meta:{color:C.muted,fontSize:7,lineHeight:12,marginTop:3},settle:{minWidth:58,minHeight:33,borderRadius:9,backgroundColor:'#17392D',alignItems:'center',justifyContent:'center'},settleText:{color:C.green,fontSize:7,fontWeight:'900'},done:{color:C.green,fontSize:7,fontWeight:'900'}});
