import {HomeAIText as Text} from './HomeAIChrome';
import TextInput from './DraftTextInput';
import {AiPressable as Pressable,AiBackdrop} from './AiChrome';
import React,{useCallback,useEffect,useState} from 'react';
import {ScrollView,StyleSheet,View} from 'react-native';
import {supabase} from '../lib/supabase';
import {PREMIUM} from './designSystem';

const C={...PREMIUM.colors,purple:PREMIUM.colors.violet};
const SYSTEMS=[
 ['main','Main','Points + Level'],['wealth','Wealth / Sending','Sent Coin Points + derived level'],
 ['charm','Charm / Receiving','Received Coin Points + derived level'],['vip','VIP','Prestige Points + VIP Level 0–100'],
 ['svip','SVIP','Separate membership; manage in SVIP Center'],
];
const ACTIONS=['increment','decrement','exact_set','reset'];
const uuid=()=> 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0;return(c==='x'?r:(r&3|8)).toString(16)});
const shown=(v,k)=>v&&v[k]!==undefined?String(v[k]):'—';

export default function OwnerProgressionOperationsCenter({initialPublicId='',onNotice}){
 const [publicId,setPublicId]=useState(String(initialPublicId||'')),[system,setSystem]=useState('main'),[action,setAction]=useState('increment');
 const [valueKind,setValueKind]=useState('points'),[value,setValue]=useState(''),[reason,setReason]=useState('');
 const [preview,setPreview]=useState(null),[confirmation,setConfirmation]=useState(''),[history,setHistory]=useState([]);
 const [busy,setBusy]=useState(false),[freezeHours,setFreezeHours]=useState('');
 const notice=useCallback(m=>onNotice?.(m),[onNotice]),cleanId=publicId.replace(/[^0-9]/g,''),supported=system!=='svip';
 const executePhrase=preview?'EXECUTE '+preview.operation_id:'',proposed=preview?.proposed_after,current=preview?.before;
 const canPrepare=/^\d{4,}$/.test(cleanId)&&supported&&reason.trim().length>=3&&(action==='reset'||/^\d+$/.test(value));
 const loadHistory=useCallback(async()=>{if(!/^\d{4,}$/.test(cleanId))return;const {data,error}=await supabase.rpc('owner_progression_operation_history_v2',{p_public_id:Number(cleanId),p_limit:30});if(error)return notice(error.message);setHistory(Array.isArray(data)?data:[])},[cleanId,notice]);
 useEffect(()=>{setPreview(null);setConfirmation('')},[cleanId,system,action,valueKind,value]);
 const prepare=async()=>{if(!canPrepare)return notice('Permanent ID, reason, and a non-negative value are required');setBusy(true);const {data,error}=await supabase.rpc('owner_prepare_progression_operation',{p_public_id:Number(cleanId),p_system:system,p_action:action,p_value:action==='reset'?0:Number(value),p_value_kind:valueKind,p_reason:reason.trim(),p_request_id:uuid(),p_preview_ttl_minutes:15});setBusy(false);if(error){setPreview(null);return notice(error.message)}setPreview(data);setConfirmation('');notice('Preview prepared • Operation '+data.operation_id)};
 const execute=async()=>{if(!preview||confirmation!==executePhrase)return notice('Type '+executePhrase+' exactly');setBusy(true);const {data,error}=await supabase.rpc('owner_execute_progression_operation',{p_operation_id:preview.operation_id,p_snapshot_hash:preview.snapshot_hash,p_confirmation:confirmation});setBusy(false);if(error)return notice(error.message);if(data?.status!=='completed')return notice(data?.error_message||'Backend did not complete the operation');notice('Progression updated • Audit '+data.operation_id);setPreview(null);setConfirmation('');await loadHistory()};
 const setFreeze=async frozen=>{if(!/^\d{4,}$/.test(cleanId)||!supported||reason.trim().length<3)return notice('Permanent ID and reason are required');const phrase=(frozen?'FREEZE ':'UNFREEZE ')+cleanId+' '+system.toUpperCase();if(confirmation!==phrase)return notice('Type '+phrase+' in confirmation');const hours=freezeHours?Number(freezeHours):null;if(frozen&&freezeHours&&(!Number.isFinite(hours)||hours<=0))return notice('Freeze hours must be positive');setBusy(true);const {data,error}=await supabase.rpc('owner_set_progression_freeze_v2',{p_public_id:Number(cleanId),p_system:system,p_frozen:frozen,p_reason:reason.trim(),p_request_id:uuid(),p_confirmation:confirmation,p_expires_at:frozen&&hours?new Date(Date.now()+hours*3600000).toISOString():null});setBusy(false);if(error)return notice(error.message);notice(system.toUpperCase()+' '+(data.frozen?'frozen':'unfrozen')+' • Audit '+data.operation_id);setConfirmation('');await loadHistory()};
 const reverse=async row=>{const phrase='REVERSE '+row.operation_id;if(confirmation!==phrase)return notice('Founder only: type '+phrase+' in confirmation');setBusy(true);const {data,error}=await supabase.rpc('owner_reverse_progression_operation',{p_operation_id:row.operation_id,p_reason:reason.trim(),p_request_id:uuid(),p_confirmation:confirmation});setBusy(false);if(error)return notice(error.message);if(data?.status!=='completed')return notice(data?.error_message||'Reversal requires manual review');notice('Reversed • Audit '+data.operation_id);setConfirmation('');await loadHistory()};

 return <View style={s.shell}>
  <Text style={s.eyebrow}>OWNER PROGRESSION • BACKEND VERIFIED</Text><Text style={s.title}>Progression Operations</Text>
  <Text style={s.banner}>SOURCE COMPLETE — PROD NOT APPLIED. Automatic gift freeze guard activates only after migration approval.</Text>
  <TextInput value={publicId} onChangeText={v=>setPublicId(v.replace(/[^0-9]/g,''))} keyboardType="number-pad" placeholder="Permanent / Public ID" placeholderTextColor={C.muted} style={s.input}/>
  <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.row}>{SYSTEMS.map(([key,label,desc])=><Pressable key={key} onPress={()=>setSystem(key)} style={[s.chip,system===key&&s.chipOn]}><Text style={s.chipLabel}>{label}</Text><Text style={s.chipSub}>{desc}</Text></Pressable>)}</ScrollView>
  {system==='svip'?<Text style={s.info}>SVIP does not reuse VIP columns. Open SVIP Center for membership grant/expiry controls.</Text>:<>
   <View style={s.row}>{ACTIONS.map(item=><Pressable key={item} onPress={()=>setAction(item)} style={[s.action,action===item&&s.actionOn]}><Text style={s.actionText}>{item.replace('_',' ').toUpperCase()}</Text></Pressable>)}</View>
   <View style={s.row}><Pressable onPress={()=>setValueKind('points')} style={[s.kind,valueKind==='points'&&s.kindOn]}><Text style={s.actionText}>POINTS</Text></Pressable><Pressable onPress={()=>setValueKind('level')} style={[s.kind,valueKind==='level'&&s.kindOn]}><Text style={s.actionText}>DERIVED LEVEL</Text></Pressable></View>
   {action!=='reset'?<TextInput value={value} onChangeText={v=>setValue(v.replace(/[^0-9]/g,''))} keyboardType="number-pad" placeholder={valueKind==='level'?'Level value':'Non-negative points'} placeholderTextColor={C.muted} style={s.input}/>:null}
   <TextInput value={reason} onChangeText={setReason} placeholder="Mandatory reason" placeholderTextColor={C.muted} style={s.input}/>
   <Pressable disabled={busy||!canPrepare} onPress={prepare} style={[s.primary,(busy||!canPrepare)&&s.disabled]}><Text style={s.primaryText}>{busy?'WORKING…':'PREPARE PREVIEW'}</Text></Pressable>
   {preview?<View style={s.preview}><Text style={s.previewTitle}>Operation {preview.operation_id}</Text><Text style={s.value}>Current: {shown(current,'points')} pts • Level {shown(current,'level')}</Text><Text style={s.value}>Proposed: {shown(proposed,'points')} pts • Level {shown(proposed,'level')}</Text><Text style={s.warning}>{(preview.warnings||[]).join(' • ')||'Current state and target reload at execute time.'}</Text><TextInput value={confirmation} onChangeText={setConfirmation} autoCapitalize="characters" placeholder={executePhrase} placeholderTextColor={C.muted} style={s.input}/><Pressable disabled={busy||confirmation!==executePhrase} onPress={execute} style={[s.primary,(busy||confirmation!==executePhrase)&&s.disabled]}><Text style={s.primaryText}>EXECUTE BACKEND OPERATION</Text></Pressable></View>:null}
   <View style={s.freeze}><Text style={s.previewTitle}>Per-system freeze</Text><Text style={s.warning}>Existing value and wallet remain unchanged. Gift deltas are recorded as suppressed; no automatic replay.</Text><TextInput value={freezeHours} onChangeText={v=>setFreezeHours(v.replace(/[^0-9]/g,''))} keyboardType="number-pad" placeholder="Optional expiry hours" placeholderTextColor={C.muted} style={s.input}/><TextInput value={confirmation} onChangeText={setConfirmation} autoCapitalize="characters" placeholder={'FREEZE '+cleanId+' '+system.toUpperCase()} placeholderTextColor={C.muted} style={s.input}/><View style={s.row}><Pressable disabled={busy} onPress={()=>setFreeze(true)} style={s.danger}><Text style={s.primaryText}>FREEZE</Text></Pressable><Pressable disabled={busy} onPress={()=>setFreeze(false)} style={s.secondary}><Text style={s.primaryText}>UNFREEZE</Text></Pressable></View></View>
  </>}
  <Pressable disabled={busy||!/^\d{4,}$/.test(cleanId)} onPress={loadHistory} style={s.secondary}><Text style={s.primaryText}>LOAD AUDIT HISTORY</Text></Pressable>
  {history.map(row=><View key={row.operation_id} style={s.history}><Text style={s.previewTitle}>{row.action} • {row.system} • {row.status}</Text><Text style={s.value}>ID {cleanId} • Actor {row.actor_public_id} • {new Date(row.created_at).toLocaleString()}</Text><Text style={s.value}>Before {shown(row.before_state,'points')} → After {shown(row.after_state,'points')}</Text><Text style={s.warning}>{row.reason}{row.reversal_of?' • reversal of '+row.reversal_of:''}</Text>{row.status==='completed'&&!row.reversal_of?<Pressable onPress={()=>reverse(row)} style={s.reverse}><Text style={s.reverseText}>FOUNDER REVERSAL</Text></Pressable>:null}</View>)}
 </View>;
}
const s=StyleSheet.create({shell:{marginTop:14,borderRadius:20,borderWidth:1,borderColor:'#39415B',backgroundColor:'#111724',padding:13},eyebrow:{color:C.cyan,fontSize:7,fontWeight:'900'},title:{color:C.text,fontSize:16,fontWeight:'900',marginTop:3},banner:{color:'#FFD887',backgroundColor:'#2A2315',borderRadius:10,padding:8,fontSize:7,lineHeight:11,marginTop:8},input:{minHeight:43,borderRadius:12,borderWidth:1,borderColor:'#343C52',backgroundColor:'#0B101A',color:C.text,paddingHorizontal:11,marginTop:8,fontSize:9},row:{flexDirection:'row',gap:6,marginTop:8},chip:{width:150,minHeight:52,borderRadius:11,borderWidth:1,borderColor:'#343C52',padding:8,justifyContent:'center'},chipOn:{backgroundColor:'#392D83',borderColor:C.cyan},chipLabel:{color:C.text,fontSize:9,fontWeight:'900'},chipSub:{color:C.muted,fontSize:6.5,marginTop:3},action:{flex:1,minHeight:36,borderRadius:10,backgroundColor:'#171D2A',alignItems:'center',justifyContent:'center'},actionOn:{backgroundColor:'#5039B8'},actionText:{color:C.text,fontSize:6.5,fontWeight:'900'},kind:{flex:1,minHeight:34,borderRadius:10,borderWidth:1,borderColor:'#343C52',alignItems:'center',justifyContent:'center'},kindOn:{borderColor:C.cyan,backgroundColor:'#18303B'},primary:{minHeight:44,borderRadius:12,backgroundColor:'#67407C',alignItems:'center',justifyContent:'center',marginTop:8},primaryText:{color:'#fff',fontSize:8,fontWeight:'900'},secondary:{flex:1,minHeight:40,borderRadius:11,backgroundColor:'#25334A',alignItems:'center',justifyContent:'center',marginTop:8},danger:{flex:1,minHeight:40,borderRadius:11,backgroundColor:'#8C304A',alignItems:'center',justifyContent:'center'},disabled:{opacity:.4},preview:{borderRadius:14,backgroundColor:'#0C2029',borderWidth:1,borderColor:'#31566A',padding:10,marginTop:9},previewTitle:{color:C.text,fontSize:9,fontWeight:'900'},value:{color:C.cyan,fontSize:7.5,marginTop:5},warning:{color:C.muted,fontSize:7,lineHeight:11,marginTop:5},freeze:{borderRadius:14,backgroundColor:'#211922',borderWidth:1,borderColor:'#604052',padding:10,marginTop:9},info:{color:'#E7C7FF',fontSize:8,lineHeight:13,padding:10,marginTop:8,backgroundColor:'#251D38',borderRadius:12},history:{borderRadius:12,borderWidth:1,borderColor:'#313A50',padding:9,marginTop:7},reverse:{marginTop:7,alignSelf:'flex-start',padding:7,borderRadius:8,borderWidth:1,borderColor:'#8C5266'},reverseText:{color:'#FF9DB4',fontSize:6.5,fontWeight:'900'}});

