import {HomeAIText as Text} from './HomeAIChrome';
import TextInput from './DraftTextInput';
import {AiPressable as Pressable,AiBackdrop} from './AiChrome';
import React,{useCallback,useState} from 'react';
import {ScrollView,StyleSheet,View} from 'react-native';
import {supabase} from '../lib/supabase';
import {PREMIUM} from './designSystem';
const C={...PREMIUM.colors,purple:PREMIUM.colors.violet};
const makeId=()=> 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0;return(c==='x'?r:(r&3|8)).toString(16)});
const GROUPS=[['Progression',[['main','Main — points + level 0'],['wealth','Wealth / Sending'],['charm','Charm / Receiving'],['vip','VIP + prestige points']]],['Finance',[['coins','Coins',1],['diamonds','Diamonds',1],['seller_balance','Seller balance',1],['seller_status','Seller status',1]]],['Membership & grants',[['svip','SVIP lifecycle + derived grants',1],['cosmetics','Expiring non-purchased cosmetics'],['reward_grants','Eligible award/reward grants'],['roles','Roles',1],['permission_overrides','Permission overrides',1]]],['Organizations & relationships',[['family_membership','Family non-owner membership',1],['agency_membership','Agency non-owner membership',1],['relationships','CP / Affinity End lifecycle',1],['room_membership','Room non-owner membership',1],['room_rewards','Room rewards (history preserved)']]],['Restrictions — canonical and individually isolated',[['wallet_freeze','Wallet freeze',1],['main_freeze','Main freeze',1],['wealth_freeze','Wealth freeze',1],['charm_freeze','Charm freeze',1],['vip_freeze','VIP freeze',1],['account_restriction','Account / access ban',1],['dp_restriction','Profile / DP restriction',1],['typing_restriction','Typing restriction',1],['emoji_restriction','Emoji restriction',1],['message_restriction','Chat / message restriction',1],['room_join_restriction','Room join blocks',1]]]];
const DEFAULTS=['main','wealth','charm','vip'];
const TABS=[['single','Single ID'],['selected','Selected IDs'],['country','Country'],['all','All users']];
const Button=({title,onPress,disabled,danger})=><Pressable disabled={disabled} onPress={onPress} style={[s.button,danger&&s.danger,disabled&&s.disabled]}><Text style={s.buttonText}>{title}</Text></Pressable>;
export default function OwnerSafeResetV3Center({onNotice}){
 const [scope,setScope]=useState('single'),[publicId,setPublicId]=useState(''),[selectedIds,setSelectedIds]=useState(''),[country,setCountry]=useState(''),[selected,setSelected]=useState(DEFAULTS),[reason,setReason]=useState(''),[preview,setPreview]=useState(null),[history,setHistory]=useState([]),[confirmation,setConfirmation]=useState(''),[second,setSecond]=useState(''),[busy,setBusy]=useState(false),[batch,setBatch]=useState(null);
 const notice=x=>onNotice?.(x),cleanId=publicId.replace(/[^0-9]/g,'');
 const toggle=k=>{setSelected(v=>v.includes(k)?v.filter(x=>x!==k):[...v,k]);setPreview(null)};
 const rpc=async(name,args)=>{setBusy(true);const out=await supabase.rpc(name,args);setBusy(false);if(out.error){notice(out.error.message);throw out.error}return out.data};
 const prepare=async()=>{if(selected.length<1||reason.trim().length<5)return notice('Choose categories and enter a clear reason');setConfirmation('');setSecond('');try{if(scope==='single'){if(!/^\d{4,}$/.test(cleanId))return notice('Enter a valid permanent ID');const data=await rpc('owner_prepare_safe_reset_v3_complete',{p_public_id:Number(cleanId),p_categories:selected,p_reason:reason.trim(),p_request_id:makeId(),p_preview_ttl_minutes:15});setPreview(data);setBatch(null)}else{const ids=selectedIds.split(/[\s,]+/).filter(Boolean).map(Number).filter(Number.isSafeInteger);const data=await rpc('owner_prepare_safe_reset_v3_batch',{p_scope_type:scope,p_selected_public_ids:scope==='selected'?ids:null,p_country_code:scope==='country'?country.trim().toUpperCase():null,p_categories:selected,p_reason:reason.trim(),p_request_id:makeId(),p_max_targets:1000});setBatch(data);setPreview(null)}}catch(_){}};
 const execute=async()=>{if(!preview)return;try{const data=await rpc('owner_execute_safe_reset_v3_complete',{p_operation_id:preview.operation_id,p_snapshot_hash:preview.snapshot_hash,p_confirmation:confirmation,p_red_zone_confirmation:second||null});if(data?.status!=='completed')return notice(data?.error_message||'Backend did not complete reset');notice('Completed • Audit '+data.operation_id);setPreview(null);await loadHistory()}catch(_){}};
 const confirmBatch=async()=>{if(!batch)return;try{const data=await rpc('owner_confirm_safe_reset_v3_batch',{p_job_id:batch.job_id,p_snapshot_hash:batch.snapshot_hash,p_confirmation:confirmation,p_second_confirmation:second});setBatch({...batch,...data});notice('Batch ready; no target changes until a chunk is processed')}catch(_){}};
 const batchAction=async action=>{if(!batch)return;try{const name=action==='process'?'owner_process_safe_reset_v3_batch_chunk':action==='status'?'owner_safe_reset_v3_batch_status':'owner_control_safe_reset_v3_batch';const args=action==='process'?{p_job_id:batch.job_id,p_chunk_size:25}:action==='status'?{p_job_id:batch.job_id}:{p_job_id:batch.job_id,p_action:action};const data=await rpc(name,args);setBatch({...batch,...data});notice('Batch '+(data.status||action))}catch(_){}};
 const loadHistory=useCallback(async()=>{if(!/^\d{4,}$/.test(cleanId))return notice('Single public ID required for history');try{setHistory(await rpc('owner_safe_reset_v3_complete_history',{p_public_id:Number(cleanId),p_limit:30})||[])}catch(_){}},[cleanId]);
 const reverse=async row=>{try{const data=await rpc('owner_reverse_safe_reset_v3_complete',{p_operation_id:row.operation_id,p_reason:reason.trim(),p_request_id:makeId(),p_confirmation:confirmation});notice(data?.status==='reversed'?'Restored • '+data.operation_id:(data?.error_code||'MANUAL_REVIEW_REQUIRED'));await loadHistory()}catch(_){}};
 return <View style={s.shell}><Text style={s.eyebrow}>SAFE RESET V3 • PREVIEW FIRST</Text><Text style={s.title}>Reset & Recovery</Text><Text style={s.legacy}>Legacy Country/All destructive RPCs are disabled. Bulk tabs use only the Founder-only resumable engine.</Text>
  <ScrollView horizontal contentContainerStyle={s.tabs}>{TABS.map(([k,l])=><Pressable key={k} onPress={()=>{setScope(k);setPreview(null);setBatch(null)}} style={[s.tab,scope===k&&s.tabOn]}><Text style={s.tabText}>{l}</Text></Pressable>)}</ScrollView>
  {scope==='single'?<TextInput value={publicId} onChangeText={v=>setPublicId(v.replace(/[^0-9]/g,''))} keyboardType="number-pad" placeholder="Permanent / Public ID" placeholderTextColor={C.muted} style={s.input}/>:null}{scope==='selected'?<TextInput value={selectedIds} onChangeText={setSelectedIds} placeholder="Public IDs separated by comma" placeholderTextColor={C.muted} style={s.input}/>:null}{scope==='country'?<TextInput value={country} onChangeText={setCountry} autoCapitalize="characters" maxLength={2} placeholder="ISO country code" placeholderTextColor={C.muted} style={s.input}/>:null}{scope!=='single'?<Text style={s.redText}>FOUNDER ONLY • max 1,000 frozen targets • chunks of 25 • protected IDs excluded</Text>:null}
  <Text style={s.policy}>Default preserve: identity/profile, SVIP, balances, cosmetics, Seller, Family, Agency, CP, roles, permissions, owned entities, restrictions and history. Only checked modules change.</Text>
  {GROUPS.map(([name,items])=><View key={name}><Text style={s.group}>{name}</Text><View style={s.grid}>{items.map(([key,label,red])=><Pressable key={key} onPress={()=>toggle(key)} style={[s.item,selected.includes(key)&&s.itemOn,red&&s.redItem]}><Text style={s.check}>{selected.includes(key)?'✓':'○'}</Text><View style={s.flex}><Text style={s.itemText}>{label}</Text>{red?<Text style={s.redLabel}>RED ZONE • FOUNDER</Text>:null}</View></Pressable>)}</View></View>)}
  <TextInput value={reason} onChangeText={setReason} placeholder="Mandatory reason" placeholderTextColor={C.muted} style={s.input}/><Button disabled={busy} onPress={prepare} title={busy?'WORKING…':'PREPARE EXACT PREVIEW'}/>{preview?<Preview data={preview}/>:null}{batch?<Batch data={batch}/>:null}
  {(preview||batch)&&<><TextInput value={confirmation} onChangeText={setConfirmation} autoCapitalize="characters" placeholder={preview?'RESET V3 '+cleanId+' '+preview.operation_id:'BULK RESET V3 '+batch.job_id} placeholderTextColor={C.muted} style={s.input}/><TextInput value={second} onChangeText={setSecond} autoCapitalize="characters" placeholder={preview?'RED ZONE '+preview.operation_id:'BULK CONFIRM '+batch.job_id} placeholderTextColor="#D392A2" style={[s.input,s.redInput]}/>{preview?<Button danger disabled={busy} onPress={execute} title="EXECUTE SELECTED MODULES"/>:batch.status==='prepared'?<Button danger disabled={busy} onPress={confirmBatch} title="CONFIRM FROZEN TARGET SET"/>:null}</>}
  {batch&&['ready','running','paused','partially_failed'].includes(batch.status)?<View>{['process','status','pause','resume','retry_failed'].map(x=><Button key={x} disabled={busy} onPress={()=>batchAction(x)} title={x.replace('_',' ').toUpperCase()}/>)}</View>:null}
  {scope==='single'?<><Button disabled={busy} onPress={loadHistory} title="LOAD HISTORY"/>{history.map(row=><View key={row.operation_id} style={s.card}><Text style={s.cardTitle}>{row.status} • {(row.categories||[]).join(', ')}</Text><Text style={s.meta}>{new Date(row.created_at).toLocaleString()} • actor {row.actor_public_id}</Text><Text style={s.warning}>{row.reversal_status}{row.reversal_status==='conflict_manual_review'?' • MANUAL REVIEW':''}</Text>{row.status==='completed'&&row.reversal_status==='eligible'?<Button danger onPress={()=>reverse(row)} title="FOUNDER CONFLICT-AWARE RESTORE"/>:null}</View>)}</>:null}<EntityLifecycle onNotice={notice}/></View>;
}
function Preview({data}){return <View style={s.card}><AiBackdrop opacity={.22}/><Text style={s.cardTitle}>Operation {data.operation_id}</Text><Text style={s.meta}>Expires: {data.preview_expires_at||'15 minutes'}</Text><Text style={s.meta}>Tables: {(data.affected_tables||[]).join(', ')||'—'}</Text><Text style={s.meta}>Counts: {JSON.stringify(data.record_counts||{})}</Text>{(data.warnings||[]).map((w,i)=><Text key={i} style={s.warning}>⚠ {w}</Text>)}<ScrollView style={s.json}><Text style={s.jsonText}>{JSON.stringify(data.before_state||{},null,2)}</Text></ScrollView></View>}
function Batch({data}){return <View style={s.card}><AiBackdrop opacity={.22}/><Text style={s.cardTitle}>Batch {data.job_id} • {data.status}</Text>{data.error_code?<Text style={s.warning}>BLOCKED • {data.error_code} — full Country/All scope exceeds the safe limit; nothing can execute.</Text>:null}<Text style={s.meta}>Entire scope {data.total_scope_count||0} • eligible {data.eligible_count||0} • frozen {data.target_count||0} • protected {data.excluded_count||0} • remaining outside frozen set {data.remaining_scope_count||0}</Text><Text style={s.meta}>Success {data.success_count||0} • failed {data.failure_count||0} • manual {data.manual_review_count||0}</Text><ScrollView style={s.json}>{(data.targets||data.exact_targets||[]).map((x,i)=><Text key={i} style={s.jsonText}>#{x.ordinal||i+1} ID {x.public_id} • {x.status}{x.error_code?' • '+x.error_code:''}</Text>)}</ScrollView></View>}
function EntityLifecycle({onNotice}){const [type,setType]=useState('family'),[id,setId]=useState(''),[action,setAction]=useState('transfer'),[target,setTarget]=useState(''),[reason,setReason]=useState(''),[preview,setPreview]=useState(null),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false);const call=async()=>{setBusy(true);const {data,error}=await supabase.rpc('owner_prepare_entity_lifecycle',{p_entity_type:type,p_entity_id:id.trim(),p_action:action,p_target_owner_public_id:target?Number(target):null,p_reason:reason.trim(),p_request_id:makeId()});setBusy(false);if(error)return onNotice(error.message);setPreview(data)};const run=async()=>{setBusy(true);const {data,error}=await supabase.rpc('owner_execute_entity_lifecycle',{p_operation_id:preview.operation_id,p_snapshot_hash:preview.snapshot_hash,p_confirmation:confirm});setBusy(false);if(error)return onNotice(error.message);onNotice('Entity operation '+data.status+' • '+data.operation_id);setPreview(null)};return <View style={s.entity}><Text style={s.group}>Owned Entity Lifecycle — never part of reset</Text><Text style={s.policy}>Transfer requires a verified target. Archive/restore preserves members, rewards and settlement history.</Text><View style={s.tabs}>{['family','agency','room'].map(x=><Pressable key={x} onPress={()=>setType(x)} style={[s.tab,type===x&&s.tabOn]}><Text style={s.tabText}>{x}</Text></Pressable>)}</View><View style={s.tabs}>{['transfer','archive','restore','orphan_repair'].map(x=><Pressable key={x} onPress={()=>setAction(x)} style={[s.tab,action===x&&s.tabOn]}><Text style={s.tabText}>{x}</Text></Pressable>)}</View><TextInput value={id} onChangeText={setId} placeholder={type==='room'?'Room public ID':'Organization UUID'} placeholderTextColor={C.muted} style={s.input}/>{['transfer','orphan_repair'].includes(action)?<TextInput value={target} onChangeText={setTarget} keyboardType="number-pad" placeholder="Verified target owner public ID" placeholderTextColor={C.muted} style={s.input}/>:null}<TextInput value={reason} onChangeText={setReason} placeholder="Mandatory lifecycle reason" placeholderTextColor={C.muted} style={s.input}/><Button disabled={busy} onPress={call} title="PREVIEW ENTITY OPERATION"/>{preview?<><Preview data={preview}/><TextInput value={confirm} onChangeText={setConfirm} autoCapitalize="characters" placeholder={'ENTITY '+action.toUpperCase()+' '+id+' '+preview.operation_id} placeholderTextColor={C.muted} style={s.input}/><Button danger disabled={busy} onPress={run} title="EXECUTE ENTITY OPERATION"/></>:null}</View>}
const s=StyleSheet.create({shell:{marginTop:14,borderRadius:20,borderWidth:1,borderColor:'#39415B',backgroundColor:'#111724',padding:13},eyebrow:{color:C.cyan,fontSize:7,fontWeight:'900'},title:{color:C.text,fontSize:16,fontWeight:'900',marginTop:3},legacy:{color:'#FFB5C5',backgroundColor:'#321822',borderRadius:10,padding:9,fontSize:7,lineHeight:11,marginTop:8},tabs:{flexDirection:'row',flexWrap:'wrap',gap:6,marginTop:8},tab:{paddingHorizontal:10,minHeight:34,borderRadius:10,borderWidth:1,borderColor:'#354057',alignItems:'center',justifyContent:'center'},tabOn:{backgroundColor:'#29306A',borderColor:C.cyan},tabText:{color:C.text,fontSize:7,fontWeight:'900',textTransform:'uppercase'},policy:{color:C.muted,fontSize:7.5,lineHeight:12,marginTop:9},redText:{color:'#FF9DB4',fontSize:7,fontWeight:'900',marginTop:8},group:{color:C.cyan,fontSize:8,fontWeight:'900',marginTop:12},input:{minHeight:43,borderRadius:12,borderWidth:1,borderColor:'#343C52',backgroundColor:'#0B101A',color:C.text,paddingHorizontal:11,marginTop:8,fontSize:9},grid:{flexDirection:'row',flexWrap:'wrap',gap:6,marginTop:7},item:{width:'48%',minHeight:48,borderRadius:11,borderWidth:1,borderColor:'#343C52',padding:8,flexDirection:'row',alignItems:'center',gap:7},itemOn:{backgroundColor:'#29306A',borderColor:C.cyan},redItem:{borderColor:'#663646'},check:{color:C.cyan,fontSize:15,fontWeight:'900'},flex:{flex:1},itemText:{color:C.text,fontSize:7.5,fontWeight:'900'},redLabel:{color:'#FF8FA9',fontSize:5.5,fontWeight:'900',marginTop:2},button:{minHeight:42,borderRadius:11,backgroundColor:'#67407C',alignItems:'center',justifyContent:'center',marginTop:8,paddingHorizontal:10},danger:{backgroundColor:'#9C3150'},buttonText:{color:'#fff',fontSize:7.5,fontWeight:'900'},disabled:{opacity:.4},card:{borderRadius:14,backgroundColor:'#0D202A',borderWidth:1,borderColor:'#31566A',padding:10,marginTop:9},cardTitle:{color:C.text,fontSize:9,fontWeight:'900'},meta:{color:C.cyan,fontSize:7,marginTop:5},warning:{color:'#FFBE88',fontSize:7,lineHeight:11,marginTop:5},json:{maxHeight:170,backgroundColor:'#080D14',borderRadius:9,padding:7,marginTop:7},jsonText:{color:'#AAB4C8',fontSize:6,lineHeight:9},redInput:{borderColor:'#7D354A'},entity:{marginTop:15,borderTopWidth:1,borderTopColor:'#364158',paddingTop:4}});

