import {makeRequestId} from './requestId';
import {HomeAIText as Text} from './HomeAIChrome';
import TextInput from './DraftTextInput';
import {AiPressable as Pressable,AiBackdrop} from './AiChrome';
import React,{useEffect,useState} from 'react';
import {StyleSheet,View} from 'react-native';
import {approveTop3,loadOwnerRankingReview,snapshotTop3} from './rechargeRewards';
const id=()=>makeRequestId();
export default function OwnerTop3ReviewScreen({campaignId}){const[data,setData]=useState({entries:[]}),[bundles,setBundles]=useState('[[],[],[]]'),[reason,setReason]=useState(''),[message,setMessage]=useState('');const load=async()=>{if(!campaignId)return;const r=await loadOwnerRankingReview(campaignId);setData(r.data||{entries:[]});setMessage(r.error?.message||'');};useEffect(()=>{load();},[campaignId]);const snapshot=async()=>{let b;try{b=JSON.parse(bundles)}catch{return setMessage('Reward JSON invalid')};const r=await snapshotTop3({p_campaign:campaignId,p_reward_bundles:b,p_reason:reason,p_request_id:id()});setMessage(r.error?.message||JSON.stringify(r.data));if(!r.error)load();};const approve=async()=>{const r=await approveTop3({p_snapshot:data.snapshot?.id,p_reason:reason,p_request_id:id()});setMessage(r.error?.message||JSON.stringify(r.data));if(!r.error)load();};return <View style={s.card}><AiBackdrop opacity={.22}/><Text style={s.h}>Closed campaign Top-3 review</Text><Text style={s.meta}>Tie-break: total ↓ · reached final total earlier · stable user UUID</Text>{data.entries?.map(e=><Text key={e.rank} style={s.line}>#{e.rank} ID {e.public_id} · {e.eligible_total} · reached {e.reached_total_at} · grant {e.grant_request_id||'pending'}</Text>)}{data.snapshot?.refund_review_required&&<Text style={s.warn}>Refund/reversal detected — manual review required. Approved snapshot is not rewritten.</Text>}<TextInput value={bundles} onChangeText={setBundles} multiline style={s.input}/><TextInput value={reason} onChangeText={setReason} placeholder="Mandatory approval reason" placeholderTextColor="#64748b" style={s.input}/><View style={s.row}><B t="Calculate draft snapshot" f={snapshot}/><B t="Approve & grant once" f={approve} disabled={!data.snapshot||data.snapshot.status!=='draft'}/></View><Text style={s.msg}>{message}</Text></View>}
const B=({t,f,disabled})=><Pressable disabled={disabled} onPress={f} style={[s.b,disabled&&{opacity:.35}]}><Text style={s.bt}>{t}</Text></Pressable>;const s=StyleSheet.create({card:{padding:12,backgroundColor:'#10182d',borderRadius:14,marginTop:12},h:{color:'#fff',fontSize:17,fontWeight:'900'},meta:{color:'#a5b4fc',marginVertical:6},line:{color:'#e2e8f0',marginVertical:3},warn:{color:'#fb7185',fontWeight:'800',marginVertical:7},input:{color:'#fff',backgroundColor:'#0b1224',padding:9,borderRadius:8,minHeight:44,marginTop:7},row:{flexDirection:'row',flexWrap:'wrap'},b:{backgroundColor:'#6d28d9',padding:10,borderRadius:8,margin:4},bt:{color:'#fff',fontWeight:'800'},msg:{color:'#67e8f9',marginTop:8}});

