import {HomeAIText as Text} from './HomeAIChrome';
import {AiPressable as Pressable,AiBackdrop} from './AiChrome';
import React,{useCallback,useEffect,useRef,useState} from 'react';
import {ActivityIndicator,Modal,ScrollView,StyleSheet,View} from 'react-native';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import {supabase} from '../lib/supabase';
import OwnerIdentityCenter from './OwnerIdentityCenter';
import OwnerBanCenter from './OwnerBanCenter';
import OwnerSvipManage from './OwnerSvipManage';
const uuid=()=>globalThis.crypto?.randomUUID?.()||'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0;return(c==='x'?r:(r&3|8)).toString(16)});
const Button=({children,onPress,disabled})=><Pressable disabled={disabled} style={[s.button,disabled&&{opacity:.4}]} onPress={onPress}><Text style={s.buttonText}>{children}</Text></Pressable>;
export default function OwnerProfileManage({visible,profile,onClose,onChanged}){
  const insets=useSafeAreaInsets(),lock=useRef(false),epochRef=useRef(0);
  const [busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[target,setTarget]=useState(null),[preview,setPreview]=useState(null);
  const publicId=Number(profile?.public_id||profile?.publicId);
  const refresh=useCallback(async()=>{const epoch=epochRef.current;const {data,error}=await supabase.rpc('owner_authority_dashboard',{p_public_id:publicId});if(error)throw error;if(epoch===epochRef.current)setTarget(data?.profile||null);},[publicId]);
  const run=async(fn,message)=>{if(lock.current)return;const epoch=epochRef.current;lock.current=true;setBusy(true);setNotice('');try{await fn();if(epoch!==epochRef.current)return;if(fn!==refresh)await refresh();if(epoch!==epochRef.current)return;if(message){setNotice(message);onChanged?.();}}catch(e){if(epoch===epochRef.current)setNotice(e.message||'Action failed. Please retry.');}finally{if(epoch===epochRef.current){lock.current=false;setBusy(false);}}};
  useEffect(()=>{epochRef.current++;lock.current=false;setBusy(false);setTarget(null);setPreview(null);if(visible&&publicId)run(refresh);return()=>{epochRef.current++;lock.current=false;}},[visible,publicId,refresh]);
  const rpc=async(name,args)=>{const r=await supabase.rpc(name,args);if(r.error)throw r.error;return r.data;};
  const changeVip=async(delta)=>{const args={p_public_id:publicId,p_action:delta>0?'increment':'decrement',p_value:1,p_reason:'Owner profile VIP adjustment',p_expected_level:Number(target.vip_level||0)};const result=await rpc('owner_mutate_vip',{...args,p_request_id:uuid(),p_preview:true});setPreview({args,result});};
  return <Modal visible={visible} animationType="slide" onRequestClose={onClose}><View style={[s.page,{paddingTop:insets.top+8,paddingBottom:insets.bottom}]}><View style={s.header}><Text style={s.title}>Owner Manage • ID {publicId||'—'}</Text><Button onPress={onClose}>Close</Button></View>{notice?<Text accessibilityLiveRegion="polite" style={s.notice}>{notice}</Text>:null}<View style={{height:22,justifyContent:'center'}}>{busy?<ActivityIndicator/>:null}</View><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.body}>{target?<><OwnerIdentityCenter key={`identity-${publicId}`} initialPublicId={publicId} lockTarget onNotice={setNotice} onSaved={onChanged}/><View style={s.row}><Text style={s.label}>General Level {target.level??0}</Text><Button disabled={busy} onPress={()=>run(()=>rpc('owner_adjust_user_level_by_public_id',{p_public_id:publicId,p_delta:-1,p_reason:'Owner profile level adjustment'}),'General Level updated')}>−</Button><Button disabled={busy} onPress={()=>run(()=>rpc('owner_adjust_user_level_by_public_id',{p_public_id:publicId,p_delta:1,p_reason:'Owner profile level adjustment'}),'General Level updated')}>+</Button></View><View style={s.row}><Text style={s.label}>VIP {target.vip_level??0}</Text><Button disabled={busy} onPress={()=>run(()=>changeVip(-1))}>−</Button><Button disabled={busy} onPress={()=>run(()=>changeVip(1))}>+</Button></View>{preview?<View style={s.preview}><Text style={s.label}>VIP {preview.result?.before?.vip_level} → {preview.result?.after?.vip_level}</Text><View style={s.row}><Button disabled={busy} onPress={()=>run(async()=>{await rpc('owner_mutate_vip',{...preview.args,p_request_id:uuid(),p_preview:false});setPreview(null)},'VIP updated')}>CONFIRM VIP CHANGE</Button><Button onPress={()=>setPreview(null)}>Cancel</Button></View></View>:null}<OwnerSvipManage key={`svip-${publicId}`} publicId={publicId} onChanged={onChanged}/><Text style={s.label}>Wallet spending</Text><View style={s.row}>{[true,false].map(active=><Button key={String(active)} disabled={busy} onPress={()=>run(()=>rpc('owner_set_wallet_freeze',{p_public_id:publicId,p_active:active,p_duration_hours:null,p_reason:'Owner profile wallet control'}),active?'Wallet spending frozen':'Wallet spending restored')}>{active?'FREEZE':'UNFREEZE'}</Button>)}</View><OwnerBanCenter key={`bans-${publicId}`} initialPublicId={publicId} onNotice={setNotice}/></>:!busy?<Button onPress={()=>run(refresh)}>Retry</Button>:null}</ScrollView></View></Modal>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#0D1220'},header:{flexDirection:'row',alignItems:'center',gap:10,paddingHorizontal:14},title:{flex:1,color:'#FFF',fontSize:17,fontWeight:'800'},body:{padding:14,gap:16,paddingBottom:30},notice:{color:'#8BE7E0',padding:14},row:{flexDirection:'row',alignItems:'center',flexWrap:'wrap',gap:10},label:{color:'#FFF',fontSize:15,flexShrink:1},button:{minHeight:44,paddingHorizontal:14,borderRadius:10,backgroundColor:'#294168',justifyContent:'center',alignItems:'center'},buttonText:{color:'#FFF',fontWeight:'800'},preview:{padding:14,gap:10,borderWidth:1,borderColor:'#658ABC',borderRadius:12}});

