import TextInput from './DraftTextInput';
import React,{useEffect,useState} from 'react';
import {Alert,Pressable,StyleSheet,Text,View} from 'react-native';
import {supabase} from '../lib/supabase';

const C={panel:'#131724',panel2:'#1B2030',line:'#2A3042',text:'#F8F9FF',muted:'#9199AD',purple:'#7558FF',cyan:'#5FE2FF',gold:'#FFD66B',green:'#5DE39A'};

export default function SellerContactEditor({targetPublicId=null,ownerMode=false,compact=false}){
 const [profile,setProfile]=useState({}),[whatsapp,setWhatsapp]=useState(''),[methods,setMethods]=useState('Bank / UPI / Wallet'),[busy,setBusy]=useState(false);
 const load=async()=>{setBusy(true);const {data,error}=await supabase.rpc(ownerMode?'owner_load_seller_contact_profile':'load_my_seller_contact_profile',ownerMode?{p_public_id:Number(targetPublicId)}:{});setBusy(false);if(error)return Alert.alert('Seller contact',error.message);const x=data||{};setProfile(x);setWhatsapp(x.whatsapp_number||'');setMethods(x.payment_methods||'Bank / UPI / Wallet');};
 useEffect(()=>{if(!ownerMode||Number(targetPublicId)>0)load()},[ownerMode,targetPublicId]);
 const save=async()=>{setBusy(true);const args=ownerMode?{p_public_id:Number(targetPublicId),p_whatsapp_number:whatsapp.trim()||null,p_payment_methods:methods.trim()||'Contact seller',p_active:profile.active!==false}:{p_whatsapp_number:whatsapp.trim()||null,p_payment_methods:methods.trim()||'Contact seller',p_active:profile.active!==false};const {data,error}=await supabase.rpc(ownerMode?'owner_save_seller_contact_profile':'save_my_seller_contact_profile',args);setBusy(false);if(error)return Alert.alert('Seller contact',error.message);setProfile(data||profile);Alert.alert('Saved',whatsapp.trim()?'Seller contact card updated.':'WhatsApp number removed.');};
 return <View style={[s.wrap,compact&&s.compact]}><Text style={s.kicker}>{ownerMode?'OWNER • SELLER CARD':'YOUR PUBLIC SELLER CARD'}</Text><Text style={s.title}>{profile.display_name||'Seller / Merchant'}{profile.public_id?' • ID '+profile.public_id:''}</Text><Text style={s.meta}>{profile.country_code||'GLOBAL'} • WhatsApp is shown only when a valid number is saved.</Text><TextInput value={whatsapp} onChangeText={setWhatsapp} keyboardType="phone-pad" placeholder="WhatsApp with country code (optional)" placeholderTextColor="#737B8E" style={s.input}/><TextInput value={methods} onChangeText={setMethods} placeholder="Payment methods / contact note" placeholderTextColor="#737B8E" style={s.input}/><View style={s.actions}><Pressable onPress={()=>setProfile(p=>({...p,active:p.active===false}))} style={[s.toggle,profile.active!==false&&s.toggleOn]}><Text style={s.buttonText}>LISTING {profile.active!==false?'ON':'OFF'}</Text></Pressable><Pressable disabled={busy} onPress={save} style={[s.save,busy&&s.disabled]}><Text style={s.buttonText}>{busy?'SAVING…':'SAVE CONTACT'}</Text></Pressable></View></View>;
}
const s=StyleSheet.create({wrap:{borderRadius:16,backgroundColor:'#17132D',borderWidth:1,borderColor:'#4B3CA0',padding:10,marginTop:9},compact:{marginTop:10},kicker:{color:C.gold,fontSize:7,fontWeight:'900',letterSpacing:.7},title:{color:C.text,fontSize:11,fontWeight:'900',marginTop:4},meta:{color:C.muted,fontSize:7,lineHeight:12,marginTop:3},input:{minHeight:42,borderRadius:11,backgroundColor:'#0D1019',borderWidth:1,borderColor:C.line,color:C.text,paddingHorizontal:10,marginTop:7},actions:{flexDirection:'row',gap:7,marginTop:7},toggle:{flex:1,minHeight:39,borderRadius:11,backgroundColor:'#3A1E29',alignItems:'center',justifyContent:'center'},toggleOn:{backgroundColor:'#17392D',borderWidth:1,borderColor:C.green},save:{flex:1,minHeight:39,borderRadius:11,backgroundColor:C.purple,alignItems:'center',justifyContent:'center'},buttonText:{color:'#fff',fontSize:7,fontWeight:'900'},disabled:{opacity:.55}});

