import{createClient}from'https://esm.sh/@supabase/supabase-js@2';
const supabase=createClient('https://zspcgyhchaqpiyujyxqp.supabase.co','sb_publishable_eUygC1Ff8vNqZHcZIOUrPw_rZb6fjQZ',{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=s=>document.querySelector(s),esc=v=>String(v??'—').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),fmt=v=>Number(v||0).toLocaleString(),uuid=()=>crypto.randomUUID();
let authority={},access={},page='overview',cache={};
const NAV=[['CORE'],['overview','◈','Overview'],['hierarchy','⌘','Authority tree'],['users','◎','Users & identity'],['rooms','◉','Rooms'],['organizations','◇','Agency & family'],['CONTROL'],['moderation','⚑','Moderation'],['finance','◫','Finance & wallets'],['commerce','◆','Recharge & payments'],['premium','✦','VIP / SVIP'],['recovery','↺','Reset & restore'],['GOVERNANCE'],['audit','≣','Audit & evidence'],['settings','⚙','Policies & settings']];
const titles=Object.fromEntries(NAV.filter(x=>x.length>1).map(x=>[x[0],x[2]]));
const toast=(m,bad=false)=>{let t=$('#toast');t.textContent=m;t.style.borderColor=bad?'#ff5577':'#8b5cf6';t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3600)};
async function rpc(name,args={}){let{data,error}=await supabase.rpc(name,args);if(error)throw error;return data}
const card=(title,value,sub='')=>`<div class="card metric"><small>${esc(title)}</small><b>${esc(value)}</b><small>${esc(sub)}</small></div>`;
const table=(cols,rows)=>`<div class="table-wrap"><table><thead><tr>${cols.map(c=>`<th>${esc(c[0])}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${cols.map(c=>`<td>${typeof c[1]==='function'?c[1](r):esc(r[c[1]])}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${cols.length}" class="empty">No scoped records found</td></tr>`}</tbody></table></div>`;
const hero=(k,t,s)=>`<div class="hero"><p class="kicker">${k}</p><h3>${t}</h3><p class="muted">${s}</p></div>`;
const perms=()=>new Set(authority.permissions||[]),has=(...p)=>authority.is_founder||p.some(x=>perms().has(x));
function renderNav(){ $('#nav').innerHTML=NAV.map(x=>x.length===1?`<div class="nav-group">${x[0]}</div>`:`<button class="nav-btn ${page===x[0]?'active':''}" data-page="${x[0]}"><span>${x[1]}</span>${x[2]}</button>`).join('');document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page))}
async function boot(){let{data:{session}}=await supabase.auth.getSession();if(!session)return showLogin();try{[access,authority]=await Promise.all([rpc('current_staff_access'),rpc('current_authority_contexts')]);if(!access?.is_staff)throw new Error('Protected staff role required');$('#login').classList.add('hidden');$('#app').classList.remove('hidden');$('#who').innerHTML=`<b>${esc(authority.primary_role||access.role)}</b><small style="display:block">${esc(session.user.email)}</small>`;$('#context').textContent=(authority.is_founder?'ROOT FOUNDER':String(authority.primary_role||'staff').replaceAll('_',' ').toUpperCase())+' • SCOPED AUTHORITY';renderNav();await go(page)}catch(e){toast(e.message,true);await supabase.auth.signOut();showLogin()}}
function showLogin(){$('#app').classList.add('hidden');$('#login').classList.remove('hidden')}
async function go(next){page=next;renderNav();$('#pageTitle').textContent=titles[page];$('#content').innerHTML='<div class="empty">Loading secure data…</div>';$('.sidebar').classList.remove('open');try{await PAGES[page]()}catch(e){$('#content').innerHTML=hero('ACCESS CHECK','Unable to load',esc(e.message));toast(e.message,true)}}
const PAGES={
 overview:async()=>{let d=await rpc('staff_dashboard_counts');cache.counts=d;$('#content').innerHTML=hero('REAL-TIME OPERATIONS','Everything important, one command surface','Live backend totals are permission-scoped. Every control below re-checks authority on the server.')+`<div class="grid">${card('Users',fmt(d.users))}${card('Rooms',fmt(d.rooms))}${card('Live rooms',fmt(d.live_rooms))}${card('Open reports',fmt(d.open_reports))}${card('Families',fmt(d.families))}${card('Agencies',fmt(d.agencies))}${card('Support',fmt(d.open_support))}${card('Staff scope',authority.roles?.length||0,authority.primary_role)}</div>`},
 hierarchy:async()=>{let[tree,roles]=await Promise.all([rpc('panel_staff_tree'),rpc('owner_role_summary')]);$('#content').innerHTML=hero('PANEL INSIDE PANEL','Authority & descendant tree','Parents see their own descendants. Children cannot inspect parents or protected sibling branches.')+`<div class="grid">${roles.slice(0,12).map(r=>card(r.display_name,fmt(r.member_count),'ranked authority')).join('')}</div><div class="section card"><div class="section-head"><h3>My visible staff branch</h3><button class="mini" data-action="assignRole">Assign scoped role</button></div><div class="tree">${(tree||[]).map(r=>`<div class="tree-node"><div class="tree-title"><b>${esc(r.display_name||r.role_key)}</b><span class="badge">${esc(r.role_key)}</span></div><small>ID ${esc(r.public_id)} · ${esc(r.context_type)}:${esc(r.context_id)}</small></div>`).join('')||'<div class="empty">No descendants assigned yet</div>'}</div></div>`;wire()},
 users:async()=>{let rows=await rpc('staff_list_users_v2',{p_search:'',p_limit:100});$('#content').innerHTML=hero('IDENTITY CONTROL','Users, login & profiles','Searchable scoped users with safe, audited actions.')+table([['ID','public_id'],['Name','display_name'],['Country','country_code'],['Status',r=>`<span class="badge">${esc(r.status)}</span>`],['Online',r=>r.is_online?'● Live':'Offline'],['Actions',r=>`<div class="actions"><button class="mini" data-action="inspectUser" data-id="${r.public_id}">Inspect</button><button class="mini" data-action="editProfile" data-id="${r.public_id}">Edit</button><button class="mini danger" data-action="ban" data-id="${r.public_id}">Restrict</button></div>`]],rows||[]);wire()},
 rooms:async()=>{let rows=await rpc('staff_list_rooms',{p_live_only:false,p_search:'',p_limit:100});$('#content').innerHTML=hero('ROOM COMMAND','Rooms, seats, access & audio','Inspect and control only rooms inside the active authority scope.')+table([['Room ID','public_id'],['Room','name'],['Owner','owner_name'],['Live',r=>r.is_live?'🔴 LIVE':'Offline'],['Members','member_count'],['Actions',r=>`<div class="actions"><button class="mini" data-action="inspectRoom" data-id="${r.public_id}">Inspect</button><button class="mini danger" data-action="roomAction" data-id="${r.public_id}">Control</button></div>`]],rows||[]);wire()},
 organizations:async()=>{let[a,f]=await Promise.all([rpc('staff_list_organizations',{p_kind:'agency',p_search:'',p_limit:100}),rpc('staff_list_organizations',{p_kind:'family',p_search:'',p_limit:100})]);let rows=[...(a||[]).map(x=>({...x,kind:'Agency'})),...(f||[]).map(x=>({...x,kind:'Family'}))];$('#content').innerHTML=hero('ORGANIZATION TREE','Agency, family, BD & LD','Ownership and member data stays inside the parent authority branch.')+table([['Type','kind'],['Name','name'],['Owner','owner_name'],['Members','member_count'],['Hosts','host_count'],['Status','status']],rows)},
 moderation:async()=>{let[q,b]=await Promise.all([rpc('owner_moderation_queue',{p_status:'open',p_limit:100}),rpc('owner_active_bans',{p_limit:100})]);$('#content').innerHTML=hero('TRUST & SAFETY','Reports, silence, ban & restore','Review evidence before applying the narrowest safe action.')+`<div class="grid">${card('Open moderation',q?.length||0)}${card('Active restrictions',b?.length||0)}${card('Permission',has('moderation.manage')?'Granted':'Scoped')}${card('Audit','Always on')}</div><div class="section">${table([['Reason','reason'],['Target','target_type'],['Created','created_at'],['Status','status']],q||[])}</div><div class="section"><div class="section-head"><h3>Active restrictions</h3><button class="mini" data-action="ban">New restriction</button></div>${table([['Target','target_value'],['Reason','reason'],['Expires','expires_at'],['Action',r=>`<button class="mini" data-action="revokeBan" data-id="${r.id}">Restore</button>`]],b||[])}</div>`;wire()},
 finance:async()=>{let rows=await rpc('owner_finance_activity_report',{p_asset:'all',p_limit:200});$('#content').innerHTML=hero('ECONOMY LEDGER','Finance, wallet & transfer','Coin/diamond adjustments are server-authoritative and permanently audited.')+`<div class="module-grid">${module('＋','Wallet adjustment','Add or remove coins/diamonds with a mandatory reason.','walletAdjust')}${module('◫','User finance report','Inspect balances and canonical ledger history.','financeReport')}${module('⇄','Seller balance','Fund or reduce seller inventory safely.','sellerAdjust')}</div><div class="section">${table([['When','created_at'],['Asset','asset'],['Amount',r=>`<b style="color:${Number(r.amount)>=0?'#59e391':'#ff5577'}">${fmt(r.amount)}</b>`],['User','target_name'],['ID','target_public_id'],['Actor','actor_name'],['Reason','note']],rows||[])}</div>`;wire()},
 commerce:async()=>{let[d,s,w]=await Promise.all([rpc('owner_load_payment_controls'),rpc('owner_settlement_queue',{p_status:'pending',p_limit:100}),rpc('owner_withdrawal_history',{p_status:'all',p_limit:100})]);$('#content').innerHTML=hero('COMMERCE CONTROL','Recharge, payments & settlements','Google Play packages, recharge rails and payouts remain backend-authoritative.')+`<div class="grid">${card('Online purchase',d?.online_purchase_enabled?'ON':'OFF')}${card('Packages',d?.packages?.length||0)}${card('Pending settlements',s?.length||0)}${card('Withdrawals',w?.length||0)}</div><div class="module-grid section">${module('◆','Payment master switch','Enable or pause new online coin purchases.','paymentToggle')}${module('⇄','Recharge limits','Seller and merchant recharge ceilings.','rechargeLimits')}${module('✓','Settlement review','Approve, reject and record external reference.','settlement')}</div>`;wire()},
 premium:async()=>{$('#content').innerHTML=hero('PREMIUM IDENTITY','VIP 0–100 · SVIP 1–10','VIP and SVIP are separate systems with separate permission and reversal controls.')+`<div class="module-grid">${module('✦','VIP control','Preview, set, add, freeze or reverse VIP operations.','vip')}${module('♛','SVIP control','Tier, expiry, revoke and reversal with version checks.','svip')}${module('◇','Cosmetics & vanity','Frames, entries, bubbles, badges and unique IDs.','cosmetic')}${module('🎁','Gift catalogue','Create, edit, feature and deactivate gifts.','gift')}</div>`;wire()},
 recovery:async()=>{$('#content').innerHTML=hero('SAFE RECOVERY','Preview → confirm → execute → reverse','Single ID, country and bounded batch reset with Founder protection and immutable snapshots.')+`<div class="module-grid">${module('↺','Single ID preview','Inspect reset impact before any mutation.','resetPreview')}${module('▦','Country / batch reset','Bounded job with snapshot hash and two confirmations.','batchReset')}${module('❄','Wallet / progression freeze','Freeze or restore the narrowest subsystem.','freeze')}${module('⌫','Entity lifecycle','Prepare delete, restore, remove or transfer for room/family/agency/CP.','lifecycle')}</div>`;wire()},
 audit:async()=>{let[o,e]=await Promise.all([rpc('owner_operation_history',{p_limit:200}),rpc('owner_evidence_vault',{p_query:'',p_entity_type:'all',p_limit:100,p_before:null})]);$('#content').innerHTML=hero('IMMUTABLE GOVERNANCE','Who · when · where · what','Operation history and evidence are read through protected server functions.')+`<div class="grid">${card('Operations',o?.length||0)}${card('Evidence records',e?.length||0)}${card('Audit access',has('audit.view')?'Granted':'Owner scoped')}${card('Retention','Backend policy')}</div><div class="section">${table([['When','created_at'],['Operation','operation_type'],['State','status'],['Actor','actor_public_id'],['Target','scope_type'],['Reason','reason']],o||[])}</div>`},
 settings:async()=>{let[d,p]=await Promise.all([rpc('owner_ops_dashboard'),rpc('owner_load_payment_controls')]);$('#content').innerHTML=hero('SYSTEM POLICY','Global operations & configuration','Changes remain permission checked, reasoned and auditable.')+`<div class="module-grid">${module('⚙','Runtime policy','Feature flags and operational switches.','runtime')}${module('📣','Notices & banners','Country/global notices, activity and campaigns.','notice')}${module('🎮','Game policy','Demo, wagering and return policies.','gamePolicy')}${module('💞','Relationship restore','CP restore price and affinity rules.','affinity')}</div>`;wire()}
};
const module=(i,t,p,a)=>`<div class="card module"><div class="icon">${i}</div><h4>${t}</h4><p>${p}</p><button class="mini" data-action="${a}">Open secure control</button></div>`;
const ACTIONS={
 assignRole:{title:'Assign scoped role',rpc:'owner_assign_multi_role',fields:[['p_user','Target user UUID'],['p_role','Role key'],['p_context_type','Context type','select','country,agency,user,seller,merchant,global'],['p_context_id','Context ID'],['p_reason','Required reason']],defaults:{p_expires_at:null,p_primary:false}},
 ban:{title:'Create account restriction',rpc:'owner_create_access_ban',fields:[['p_target_value','Permanent user ID'],['p_duration_hours','Hours (blank = permanent)','number'],['p_reason','Required reason']],defaults:{p_target_type:'account'}},
 revokeBan:{title:'Restore restricted access',rpc:'owner_revoke_access_ban',fields:[['p_reason','Required restore reason']],idKey:'p_ban'},
 walletAdjust:{title:'Adjust wallet asset',rpc:'owner_adjust_wallet_asset',fields:[['p_public_id','Permanent user ID','number'],['p_asset','Asset','select','coins,diamonds'],['p_amount','Signed whole amount','number'],['p_note','Required audit reason']]},
 sellerAdjust:{title:'Adjust seller balance',rpc:'owner_adjust_seller_balance',fields:[['p_public_id','Seller permanent ID','number'],['p_amount','Signed amount','number'],['p_note','Required audit reason']]},
 rechargeLimits:{title:'Update recharge limits',rpc:'owner_update_recharge_limits',fields:[['p_seller_recharge_max','Seller max','number'],['p_merchant_inventory_max','Merchant max','number']]},
 paymentToggle:{title:'Online coin purchase',rpc:'owner_set_online_coin_purchase',fields:[['p_enabled','Enabled','select','true,false'],['p_reason','Required reason']]},
 vip:{title:'Preview VIP operation',rpc:'owner_mutate_vip',fields:[['p_public_id','Permanent user ID','number'],['p_action','Action','select','set,add,remove,freeze,unfreeze'],['p_value','VIP value 0–100','number'],['p_reason','Required reason']],defaults:{p_request_id:null,p_expected_level:null,p_preview:true}},
 svip:{title:'Preview SVIP operation',rpc:'owner_mutate_svip',fields:[['p_public_id','Permanent user ID','number'],['p_action','Action','select','grant,extend,set_tier,revoke,freeze,unfreeze'],['p_tier','SVIP tier 1–10','number'],['p_days','Days','number'],['p_reason','Required reason']],defaults:{p_exact_expiry:null,p_request_id:null,p_expected_version:null,p_preview:true}},
 resetPreview:{title:'Preview safe reset',rpc:'owner_prepare_safe_reset_v3_complete',fields:[['p_public_id','Permanent user ID','number'],['p_categories','Categories (comma separated)'],['p_reason','Required reason']],defaults:{p_request_id:null,p_preview_ttl_minutes:15}},
 freeze:{title:'Wallet freeze / restore',rpc:'owner_set_wallet_freeze',fields:[['p_public_id','Permanent user ID','number'],['p_active','Freeze active','select','true,false'],['p_duration_hours','Hours','number'],['p_reason','Required reason']]},
 roomAction:{title:'Room control',rpc:'owner_room_action',fields:[['p_action','Action','select','close,reopen,freeze_chat,unfreeze_chat,remove_member'],['p_target_public_id','Target user ID (optional)','number'],['p_reason','Required reason']],idKey:'p_room_public_id'},
 notice:{title:'Publish system notice',rpc:'owner_publish_system_notice',fields:[['p_title','Title'],['p_body','Message'],['p_country_code','Country code (blank = global)'],['p_expires_at','Expiry ISO time']]},
 affinity:{title:'Relationship restore price',rpc:'owner_set_affinity_restore_cost',fields:[['p_coin_cost','Coin cost','number'],['p_reason','Required reason']]}
};
function wire(){document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>openAction(b.dataset.action,b.dataset.id))}
function openAction(key,id){let a=ACTIONS[key];if(!a)return toast('This advanced control opens after its safe preview contract is selected.',true);$('#dialogTitle').textContent=a.title;$('#dialogFields').innerHTML=a.fields.map(([n,l,t='text',opts])=>`<label>${l}</label>${t==='select'?`<select data-field="${n}">${opts.split(',').map(x=>`<option value="${x}">${x}</option>`).join('')}</select>`:`<input data-field="${n}" type="${t}">`}`).join('');$('#dialogSubmit').onclick=async()=>{let args={...(a.defaults||{})};document.querySelectorAll('[data-field]').forEach(el=>{let v=el.value;if(el.type==='number')v=v===''?null:Number(v);if(v==='true'||v==='false')v=v==='true';if(el.dataset.field==='p_categories')v=v.split(',').map(x=>x.trim()).filter(Boolean);args[el.dataset.field]=v});if(a.idKey)args[a.idKey]=id;try{$('#dialogSubmit').disabled=true;let d=await rpc(a.rpc,args);$('#actionDialog').close();toast('Action completed and audit recorded');await go(page);console.info('Operation result',d)}catch(e){toast(e.message,true)}finally{$('#dialogSubmit').disabled=false}};$('#actionDialog').showModal()}
$('#loginForm').onsubmit=async e=>{e.preventDefault();let b=e.submitter;b.disabled=true;b.textContent='Verifying authority…';try{let response=await fetch('https://zspcgyhchaqpiyujyxqp.supabase.co/functions/v1/panel-login',{method:'POST',headers:{'Content-Type':'application/json','apikey':'sb_publishable_eUygC1Ff8vNqZHcZIOUrPw_rZb6fjQZ'},body:JSON.stringify({login_id:$('#email').value.trim(),password:$('#password').value})});let result=await response.json();if(!response.ok||!result.session)throw new Error(result.message||'Login failed');let{error}=await supabase.auth.setSession({access_token:result.session.access_token,refresh_token:result.session.refresh_token});if(error)throw error;$('#password').value='';await boot()}catch(error){toast(error.message,true)}finally{b.disabled=false;b.textContent='Enter command center'}};
$('#resetPassword').onclick=async()=>{let email=$('#email').value.trim();if(!email)return toast('Enter official email first',true);let{error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:location.origin});toast(error?error.message:'Password recovery email sent',!!error)};
$('#logout').onclick=async()=>{await supabase.auth.signOut({scope:'local'});showLogin();toast('Signed out securely')};$('#menu').onclick=()=>$('.sidebar').classList.toggle('open');supabase.auth.onAuthStateChange((event)=>{if(event==='SIGNED_OUT')showLogin()});boot();
