const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function giftInteger(v,label,min=0,max=Number.MAX_SAFE_INTEGER){const text=String(v).trim();if(!/^\d+$/.test(text)||!Number.isSafeInteger(Number(text))||Number(text)<min||Number(text)>max)throw Error(label+' is outside its supported whole-number range');return Number(text)}
function https(value,label){const s=String(value||'').trim();if(!s)return null;const u=new URL(s);if(u.protocol!=='https:'||u.username||u.password||s.length>2000||/\s/.test(s))throw Error(label+' must be a public HTTPS URL');return s}
export function giftPayload(value,old={}){
 const max=giftInteger(value('custom_combo_max'),'Maximum combo',1,9999),combos=value('combo_quantities').split(',').map(x=>giftInteger(x,'Combo',1,max));
 if(!combos.length||combos.length>12||new Set(combos).size!==combos.length)throw Error('Use 1–12 unique combo quantities');
 const name=value('name').trim();if(!name)throw Error('Gift name required');
 return {...old,name,coin_price:giftInteger(value('coin_price'),'Coin price',1,10000000),diamond_value:giftInteger(value('diamond_value'),'Diamonds',0,10000000),category:value('category').trim(),asset_key:value('asset_key').trim(),effect_kind:value('effect_kind').trim(),effect_asset_url:https(value('effect_asset_url'),'Artwork'),sound_url:https(value('sound_url'),'Sound'),effect_duration_ms:giftInteger(value('effect_duration_ms'),'Duration milliseconds',1000,30000),combo_quantities:combos,custom_combo_max:max,allow_custom_combo:value('allow_custom_combo')==='true',active:value('active')==='true',featured:value('featured')==='true',sort_order:giftInteger(value('sort_order'),'Order'),min_vip_level:giftInteger(value('min_vip_level'),'Minimum VIP',0,100)};
}
const field=(name,title,value='',type='text')=>'<label>'+esc(title)+'</label><input name="'+name+'" type="'+type+'" value="'+esc(value)+'">';
const toggle=(name,title,value)=>'<label>'+esc(title)+'</label><select name="'+name+'"><option value="true" '+(value?'selected':'')+'>Yes</option><option value="false" '+(!value?'selected':'')+'>No</option></select>';
export async function showGiftControl({root,rpc,client,isCurrent,toast}){
 let rows=[],offset=0,search='',busy=false,revision=0;
 const safe=()=>isCurrent()&&root.isConnected;
 async function load(){const token=++revision;let query=client.from('gift_catalog').select('*').order('sort_order').order('id').range(offset,offset+99);if(search)query=query.ilike('name','%'+search.replace(/[%_]/g,'')+'%');const {data,error}=await query;if(error)throw error;if(!safe()||token!==revision)return;rows=data||[];render()}
 function render(){root.innerHTML='<div class="hero"><p class="kicker">GIFT CATALOGUE</p><h3>Original artwork, price & availability</h3><p>Active and archived gifts. Existing IDs, purchases and gift history are preserved. Financial outcomes remain server controlled.</p></div><div class="card section"><form id="giftSearch">'+field('search','Gift name',search)+'<button class="mini">Search</button></form><button class="mini" data-new>Add original gift</button><div class="table-wrap"><table><thead><tr><th>Name / stable slug</th><th>Category</th><th>Coins</th><th>Status</th><th></th></tr></thead><tbody>'+rows.map((r,i)=>'<tr><td>'+esc(r.name)+'<small style="display:block">'+esc(r.slug)+'</small></td><td>'+esc(r.category)+'</td><td>'+esc(r.coin_price)+'</td><td>'+esc(r.active?'Active':'Archived')+'</td><td><button class="mini" data-edit="'+i+'">Edit / archive</button></td></tr>').join('')+'</tbody></table></div><button class="mini" data-prev '+(!offset?'disabled':'')+'>Previous</button><button class="mini" data-next '+(rows.length<100?'disabled':'')+'>Next</button></div><div id="giftEditor"></div>';
 root.querySelector('#giftSearch').onsubmit=e=>{e.preventDefault();search=e.target.elements.search.value.trim();offset=0;load().catch(e=>safe()&&toast(e.message,true))};root.querySelector('[data-new]').onclick=()=>edit(null);root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(rows[Number(b.dataset.edit)]));root.querySelector('[data-prev]').onclick=()=>{offset=Math.max(0,offset-100);load().catch(e=>safe()&&toast(e.message,true))};root.querySelector('[data-next]').onclick=()=>{offset+=100;load().catch(e=>safe()&&toast(e.message,true))};
 }
 function edit(old){const r=old||{coin_price:1,diamond_value:0,category:'standard',asset_key:'',effect_kind:'standard',effect_duration_ms:4000,combo_quantities:[1,10,99],custom_combo_max:9999,active:false,featured:false,allow_custom_combo:true,sort_order:100,min_vip_level:0};const holder=root.querySelector('#giftEditor');holder.innerHTML='<form id="giftForm" class="card section"><h3>'+esc(old?'Edit '+r.name:'New gift draft')+'</h3>'+field('name','Name',r.name)+field('category','Category',r.category)+field('asset_key','Existing bundled asset key',r.asset_key)+field('effect_kind','Effect kind',r.effect_kind)+field('effect_asset_url','Original artwork / animation HTTPS URL',r.effect_asset_url)+field('sound_url','Sound HTTPS URL',r.sound_url)+field('coin_price','Coin price',r.coin_price,'number')+field('diamond_value','Diamond value',r.diamond_value,'number')+field('effect_duration_ms','Effect duration milliseconds (1000–30000)',r.effect_duration_ms,'number')+field('combo_quantities','Combo quantities, comma separated',r.combo_quantities.join(','))+field('custom_combo_max','Maximum combo',r.custom_combo_max,'number')+field('sort_order','Order',r.sort_order,'number')+field('min_vip_level','Minimum VIP',r.min_vip_level,'number')+toggle('allow_custom_combo','Allow custom combo',r.allow_custom_combo)+toggle('active','Active (No archives, Yes restores)',r.active)+toggle('featured','Featured',r.featured)+'<button class="primary">Save with version check</button><p>Stable slug and ID cannot be changed. Conflicts require reopening the latest record. Server audit records the actor and before/after values.</p></form>';const form=holder.querySelector('form');form.onsubmit=async e=>{e.preventDefault();if(busy||!safe())return;const value=n=>form.elements.namedItem(n).value;let payload;try{payload=giftPayload(value,r)}catch(e){return toast(e.message,true)}busy=true;form.querySelector('button').disabled=true;try{await rpc('owner_save_gift_v3',{p_gift:old?.id||null,p_values:payload,p_expected_version:old?.policy_version??null});if(!safe())return;toast('Gift saved with server audit');await load()}catch(e){if(safe())toast(e.message,true)}finally{busy=false;if(safe()&&form.isConnected)form.querySelector('button').disabled=false}};holder.scrollIntoView({block:'start'});
 }
 await load();
}
