export const KINDS=['frame','entry','bubble','badge','medal','room_frame','room_theme','nameplate','noble','emoji_pack','gift_theme'];
export const CATEGORIES=['normal','room','family','agency','rocket','birthday','noble','official','role','vip','svip','cp','recharge','sender','bestie','brother','sister','mentor'];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
export function integer(v,label){if(!/^\d+$/.test(String(v).trim())||!Number.isSafeInteger(Number(v)))throw Error(label+' must be a supported whole number');return Number(v)}
export function itemPayload(form,old=null){
 const value=n=>form.elements.namedItem(n).value;
 const visual=JSON.parse(value('visual')||'{}');if(!visual||Array.isArray(visual)||typeof visual!=='object')throw Error('Visual settings must be a JSON object');
 return {code:old?.code||value('code').trim(),name:value('name').trim(),kind:old?.kind||value('kind'),tier:value('tier'),visual,asset_url:value('asset_url').trim()||null,sound_url:value('sound_url').trim()||null,sound_key:value('sound_key').trim()||null,price_coins:integer(value('price_coins'),'Price'),duration_days:integer(value('duration_days'),'Duration'),sort_order:integer(value('sort_order'),'Order'),purchasable:value('purchasable')==='true',active:value('active')==='true'};
}
const select=(name,values,current)=>'<select name="'+name+'">'+values.map(v=>'<option '+(String(v)===String(current)?'selected ':'')+'value="'+esc(v)+'">'+esc(v)+'</option>').join('')+'</select>';
const input=(name,value='',type='text',readonly=false)=>'<input name="'+name+'" type="'+type+'" value="'+esc(value)+'" '+(readonly?'readonly':'')+'>';
const label=(title,field)=>'<label>'+esc(title)+'</label>'+field;
export async function showPropsControl({root,rpc,isCurrent,toast}){
 let offset=0,items=[],sets=[],busy=false,request=0,search='',kind='';
 const safe=()=>isCurrent()&&root.isConnected;
 async function load(){const token=++request;const data=await rpc('owner_load_props_v169',{p_search:search,p_kind:kind,p_offset:offset});if(!safe()||token!==request)return;items=data.items||[];sets=data.sets||[];render()}
 function render(){
 root.innerHTML='<div class="hero"><p class="kicker">MY PROPS CONTROL</p><h3>Catalogue & matching sets</h3><p>Edit artwork, sound, price, duration and availability. Archive hides future availability; existing grants and purchase history are retained. Set category controls catalogue placement; automatic rewards are separate rules.</p></div><div class="card section"><form id="propSearch">'+input('search',search)+select('kind',['',...KINDS],kind)+'<button class="mini">Search</button></form><div class="actions"><button class="mini" data-new-item>Add prop</button><button class="mini" data-new-set>Add matching set</button></div><div class="table-wrap"><table><thead><tr><th>Prop</th><th>Kind / tier</th><th>Price / days</th><th>Status</th><th></th></tr></thead><tbody>'+items.map((r,i)=>'<tr><td>'+esc(r.name)+'<small style="display:block">'+esc(r.code)+'</small></td><td>'+esc(r.kind)+' / '+esc(r.tier)+'</td><td>'+esc(r.price_exact)+' / '+esc(r.duration_days)+'</td><td>'+esc(r.active?'Active':'Archived')+' · '+esc(r.purchasable?'Sale':'Grant only')+'</td><td><button class="mini" data-edit-item="'+i+'">Edit / archive</button></td></tr>').join('')+'</tbody></table></div><div class="actions"><button class="mini" data-prev '+(offset===0?'disabled':'')+'>Previous</button><button class="mini" data-next '+(items.length<100?'disabled':'')+'>Next</button></div></div><div class="card section"><h3>Matching sets</h3><div class="table-wrap"><table><thead><tr><th>Set</th><th>Category</th><th>Items / status</th><th></th></tr></thead><tbody>'+sets.map((r,i)=>'<tr><td>'+esc(r.set.name)+'<small style="display:block">'+esc(r.set.code)+'</small></td><td>'+esc(r.set.category)+'</td><td>'+r.items.length+' / '+esc(r.set.active?'Active':'Archived')+'</td><td><button class="mini" data-edit-set="'+i+'">Edit membership / category</button></td></tr>').join('')+'</tbody></table></div></div><div id="propEditor"></div>';
 root.querySelector('#propSearch').onsubmit=e=>{e.preventDefault();search=e.target.elements.search.value.trim();kind=e.target.elements.kind.value;offset=0;load().catch(e=>safe()&&toast(e.message,true))};
 root.querySelector('[data-new-item]').onclick=()=>editItem(null);root.querySelector('[data-new-set]').onclick=()=>editSet(null);
 root.querySelectorAll('[data-edit-item]').forEach(b=>b.onclick=()=>editItem(items[Number(b.dataset.editItem)]));root.querySelectorAll('[data-edit-set]').forEach(b=>b.onclick=()=>editSet(sets[Number(b.dataset.editSet)]));
 root.querySelector('[data-prev]').onclick=()=>{offset=Math.max(0,offset-100);load().catch(e=>safe()&&toast(e.message,true))};root.querySelector('[data-next]').onclick=()=>{offset+=100;load().catch(e=>safe()&&toast(e.message,true))};
 }
 function editItem(old){
 const r=old||{kind:'frame',tier:'standard',visual:{},duration_days:30,sort_order:100,price_exact:'0',active:true,purchasable:false};
 const editor=root.querySelector('#propEditor');
 editor.innerHTML='<form class="card section" id="itemForm"><h3>'+esc(old?'Edit prop':'Add prop')+'</h3>'+label('Stable code',input('code',r.code,'text',!!old))+label('Name',input('name',r.name))+label('Kind',old?input('kind',r.kind,'text',true):select('kind',KINDS,r.kind))+label('Tier',select('tier',['standard','premium','vip','official'],r.tier))+label('Original artwork HTTPS URL',input('asset_url',r.asset_url))+label('Original sound HTTPS URL',input('sound_url',r.sound_url))+label('Bundled sound key',input('sound_key',r.sound_key))+label('Visual JSON (preserve existing artwork / set metadata)','<textarea name="visual" rows="8" style="width:100%">'+esc(JSON.stringify(r.visual||{},null,2))+'</textarea>')+label('Coin price',input('price_coins',r.price_exact,'number'))+label('Duration in days',input('duration_days',r.duration_days,'number'))+label('Order',input('sort_order',r.sort_order,'number'))+label('Available for sale',select('purchasable',['false','true'],r.purchasable))+label('Active (false archives)',select('active',['true','false'],r.active))+label('Required audit reason',input('reason'))+'<button class="primary" type="submit">Save prop</button><p>Existing code and kind are fixed to preserve purchases. To replace a kind, archive this item and create a new code.</p></form>';
 const form=editor.querySelector('form');form.onsubmit=e=>{e.preventDefault();submit(form,()=>rpc('owner_save_prop_v169',{p_item:itemPayload(form,old),p_revision:old?.revision||null,p_reason:form.elements.reason.value.trim()}))};editor.scrollIntoView({block:'start'});
 }
 function editSet(old){
 const r=old?.set||{category:'normal',active:false,official:false,sort_order:0};
 const editor=root.querySelector('#propEditor');
 editor.innerHTML='<form class="card section" id="setForm"><h3>Matching set</h3>'+label('Stable set code',input('code',r.code,'text',!!old))+label('Name',input('name',r.name))+label('Placement category',select('category',CATEGORIES,r.category))+label('Official protection',select('official',['false','true'],r.official))+label('Active',select('active',['false','true'],r.active))+label('Order',input('sort_order',r.sort_order,'number'))+label('Item codes, one per line','<textarea name="items" rows="11" style="width:100%">'+esc((old?.items||[]).join('\n'))+'</textarea>')+label('Required audit reason',input('reason'))+'<button class="primary" type="submit">Save set</button><p>An active set needs all nine My Props kinds. Create its items first, then paste their codes. Archive preserves existing grants. Official items cannot be sold.</p></form>';
 const form=editor.querySelector('form');form.onsubmit=e=>{e.preventDefault();submit(form,()=>rpc('owner_save_prop_set_v169',{p_set:{code:old?.set.code||form.elements.code.value.trim(),name:form.elements.name.value.trim(),category:form.elements.category.value,official:form.elements.official.value==='true',active:form.elements.active.value==='true',sort_order:integer(form.elements.sort_order.value,'Order')},p_items:form.elements.items.value.split(/\s+/).filter(Boolean),p_revision:old?.revision||null,p_reason:form.elements.reason.value.trim()}))};editor.scrollIntoView({block:'start'});
 }
 async function submit(form,action){if(busy||!safe())return;busy=true;form.querySelector('button').disabled=true;try{await action();if(!safe())return;toast('Saved with audit history');await load()}catch(e){if(safe())toast(e.message,true)}finally{busy=false;if(safe()&&form.isConnected)form.querySelector('button').disabled=false}}
 await load();
}
